### ISSUE TITLE
Can't install shopify-admin-api

### ISSUE THREAD

**Issue by Psycarlo** [Shopify/shopify-api-js#1053]
When I run `pnpm add @shopify/admin-api-client`, I get:

`@shopify/admin-api-client is not in the npm registry, or you have no permission to fetch it`

**Comment by rgaino** [comment]
Did you figure this out @Psycarlo ?

**Comment by Psycarlo** [comment]
You can use it to call stuff

`const products = await shopify.rest.Product.all({
      ...pageInfo?.nextPage?.query,
      session,
      limit: 50
    })`
