### ISSUE TITLE
What is the state of this repo?

### ISSUE THREAD

**Issue by pauldemarco** [Shopify/shopify-api-js#1061]
The docs are out of sync with the packages, and the packages are not yet published to NPM.

Is this correct?

**Comment by leonardo-ornelas** [comment]
Yep, packages are not published
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@shopify%2fapi-codegen-preset - Not found
npm ERR! 404 
npm ERR! 404  '@shopify/api-codegen-preset@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by amoser67** [comment]
@paulomarg Regarding the docs [here](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/guides/rest-resources.md), in the *Example Usage* section, the only thing that seemed to work for me was the "With a plain REST client" part. The "With REST resources" section doesn't really seem to align with the library, as far as I can tell.

When I create a "shopify" instance by calling `shopifyApi({...})`, `shopify.clients.Rest` exists on the object, but I don't see support for anything like the `shopify.rest.Product` syntax described in the latter half of the document.

Unless specific arguments passed to `shopifyApi` determine the shopify object's properties (e.g. "rest" property is only present when X arg is passed to `shopifyApi`), something seems wrong. And if they aren't wrong, then it would help to have a bit more information regarding how the constructor args map to the constructed object's properties.
