### ISSUE TITLE
Issues with Using RE2 Expressions in Shopify GraphQL Queries

### ISSUE THREAD

**Issue by errolgr** [Shopify/shopify-api-js#1134]
# Issue summary

I am encountering an issue with using RE2 regular expressions in Shopify's GraphQL API queries. [According to the Shopify documentation](https://shopify.dev/docs/api/usage/search-syntax) -- _"Shopify supports [RE2 syntax](https://github.com/google/re2/wiki/Syntax) for regular expressions."_)-- the API supports RE2 syntax for regular expressions, particularly for operations like prefix searches. However, when attempting to use RE2 expressions in my queries, they do not work as expected.

**Steps to Reproduce**

1. Construct a GraphQL query to fetch products with a title that starts with a specific string, using RE2 syntax for the prefix search.

```gql
{
  products(first: 10, query: "title:^Test") {
    edges {
      node {
        id
        title
      }
    }
  }
}
```
or suffix regex query

```gql
{
  products(first: 10, query: "title:/Test$/") {
    edges {
      node {
        id
        title
      }
    }
  }
}
```

2. Send the query to the Shopify GraphQL API using js client or graph client of your choice.
3. Observe that the query does not return the expected results.
-->

- `@shopify/shopify-api` version: 5.2.0
- Node version: 18.17.0
- Operating system: MacOS Monterey Version. 12.2.1

## Expected Behavior
The query should return products whose titles start with the specified prefix, in this case, "Test" or in the latter example products should be returned who's titles end with "Test"

## Actual Behavior
The query fails to apply the regex filter as intended and returns no products.

I would appreciate any insights or solutions to this problem, as it is critical for efficiently filtering data in my application.

**Comment by lizkenyon** [comment]
Hi there 👋 

Thank you for the detailed issue!

It looks like this is a problem, as you stated, with the API, and not with this library.

Could you report this issue to API support? You can find this in your [Partner Dashboard ](https://www.shopify.com/partners)under Support > Contact Support > API Support.

That will help route this issue to the correct team.
