### ISSUE TITLE
API Key mentioned in docs vs Client ID and Client Secret available on partners dashboard

### ISSUE THREAD

**Issue by titocosta** [Shopify/shopify-api-js#1141]
Basic question after the first hour browsing through docs to build a Shopify app on NextJS.

The documentation for [https://github.com/Shopify/shopify-api-js/tree/main/packages/shopify-api](shopify-api-js) mentions `apiKey` and `apiSecretKey`.

```
const shopify = shopifyApi({
  // The next 4 values are typically read from environment variables for added security
  apiKey: 'APIKeyFromPartnersDashboard',
  apiSecretKey: 'APISecretFromPartnersDashboard',
  scopes: ['read_products'],
  hostName: 'ngrok-tunnel-address',
  ...
});
```

However on the Partners Dashboard, I see client ID, client secret and I can ask for a temporary refresh token. There is no mention of an API Key.

Has the initialization of shopifyApi changed or how do I get started?

**Comment by lizkenyon** [comment]
Hi there 👋 

You are correct. The clientID in Partners maps to the API Key, and Client Secret to API Secret.

We don't have too much documentation on building with Nextjs, but we do have more [detailed documentation and tutorials](https://shopify.dev/docs/apps/getting-started/create) for building with [Remix](https://remix.run/) that you may want to check out. Happy Coding!
