### ISSUE TITLE
How to create session with third party domain?

### ISSUE THREAD

**Issue by chrisli-sas** [Shopify/shopify-api-js#1157]
Is there a way of using third party domain to create a session? it works fine with `myshopify.com` domain, but when I use a custom domain i get `Error: Received invalid shop argument`.
Or is there anything else I can use other than Session? I want to use my own domain for the checkout url instead of myshopify.com domain

```
const session = shopify.session.customAppSession('checkout.domain.com');

const client = new shopify.clients.Storefront({
  session,
  apiVersion: LATEST_API_VERSION,
});
```

**Comment by chrisli-sas** [comment]
> Hey! Unfortunately, the domain for the session must be a valid Shopify store, because that is the domain we'll use to query the APIs, so it can't be customized.
> 
> Shopify supports a number of different ways for you to customize checkout using apps, you can find more information [in our documentation](https://shopify.dev/docs/apps/checkout/technologies).
> 
> We use issues in this repo to track bugs in the package, but this is a case we can't really support, so I'll close the issue. If you have any more questions, I would suggest visiting the [Community Forums](https://community.shopify.com/), where you might be able to get better answers if you have questions about a specific use case.
> 
> Hope this helps!

Thank you for the response, the domain I'm trying to use is a valid Shopify store, I set it as primary domain for my Shopify store, I can use it for hostname when creating shopify object but not in session

**Comment by paulomarg** [comment]
Oh! If your domain _is_ a valid store domain, you can use [the `customShopDomains` setting](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/reference/shopifyApi.md#customshopdomains) to allow values other than `myshopify.com`.

I'll reopen this since it is a valid use case, please let me know if that works for you.

**Comment by chrisli-sas** [comment]
Thank you, is this the correct way of using customShopDomains? I'm having the same issue using this config

```
const shopify = shopifyApi({
  apiKey: '',
  apiSecretKey: '',
  apiVersion: LATEST_API_VERSION,
  isCustomStoreApp: true,
  adminApiAccessToken: '',
  isEmbeddedApp: false,
  hostName: '*.myshopify.com',
  privateAppStorefrontAccessToken: '',
  customShopDomains: ['shop.domain.ca'],
});
```

**Comment by paulomarg** [comment]
You wouldn't add the `shop` part, just `*.domain.ca`.
