### ISSUE TITLE
NEW BUG: storeAvailability locations missing

### ISSUE THREAD

**Issue by portedison** [Shopify/shopify-api-js#1261]
# Issue summary

When requesting the graphql product endpoint (https://shopify.dev/docs/api/storefront/2024-01/queries/product) the variant, storeAvailability is not returning the correct data. This is a new issue as we were previously getting the the correct data.

```
product(handle: $handle) {
    variants(first: 250) {
        edges {
            node {
                storeAvailability(first: 250) {
                    edges {
                        node {
                            location {
                                name
                            }
                            available
                        }
                    }
                }
            }
        }
    }
}
```

- `@shopify/shopify-api` version: 2023-01 and 2024-01
- Node version: 18
- Operating system: Mac

## Returned data
```
Variant 1

"node": {
          "id": "gid://shopify/ProductVariant/...",
          "title": "White",
          "sku": "FL1060509",
          "availableForSale": true,
          "currentlyNotInStock": false,
          "price": { "amount": "565.0", "currencyCode": "NZD" },
          "compareAtPrice": { "amount": "665.0", "currencyCode": "NZD" },
          "storeAvailability": { "edges": [] },
          "quantityAvailable": 10,
          "leadTime": { "key": "lead_time", "value": "14 Weeks" },}
      },

Variant 2

"node": {
          "id": "gid://shopify/ProductVariant/...",
          "title": "Grey Blue",
          "sku": "FL1060514",
          "availableForSale": true,
          "currentlyNotInStock": false,
          "price": { "amount": "565.0", "currencyCode": "NZD" },
          "compareAtPrice": { "amount": "665.0", "currencyCode": "NZD" },
          "storeAvailability": {
            "edges": [
              { "node": { "location": { "name": "Gordon Road Warehouse" }, "available": true } }
            ]
          },
          "quantityAvailable": 6,
          "leadTime": { "key": "lead_time", "value": "14 Weeks" },
        }
      },

```

## Expected behavior

We should be getting 4 locations for each. Both `availableForSale ` and `currentlyNotInStock` indicate that we have stock. Admin indicates that we have stock in all 4 locations. All locations are set to **Fulfill online orders from this location**.

## Actual behavior

We get 0 or 1 locations for each.

**Comment by lizkenyon** [comment]
Hi there 👋 

This seems to be related to the Shopify API itself and not this API library. The best places to report API issues are the [community forums,](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select). Thanks! 

Please feel free to create any issues in the repo for bugs within the library! :)
