### ISSUE TITLE
Customer deletion error: Disconnected before secure TLS was established

### ISSUE THREAD

**Issue by julianCast** [Shopify/shopify-api-js#1264]
# Issue summary

My query got thrown an error while a DB insertion (expected), so as a fallback I delete the customer as a cleanup by doing this:

```tsx
async deleteCustomer(customerId: number): Promise<void> {
    const customer = new shopify.rest.Customer({ session });
    customer.id = customerId;
    return customer.delete();
}
```

But the customer is not deleted and I get the log output shown below. 

Adding an await and using the method as the API states seems to fix the issue, is the reason that the connection was closed before performing the action?
```tsx
 async deleteCustomer(id: number): Promise<void> {
    await shopify.rest.Customer.delete({
      session,
      id,
    });
  }
```
- `@shopify/shopify-api` version: 9.0.2
- Node version: 16.17.1
- Operating system: macOS

```
"Error: Admin API Client: request to https: //my-shop-
2024.myshopify.com/admin/api/2024-01/customers/6623826772033.json Error: Admin API Client: request to https://dev-shop-2024.myshopify.com/admin/api/2024-01/customers/6623826772033.json failed, reason: Client network socket
disconnected before secure TLS connection was established
at e (webpack:///node_modules/@shopify/admin-api-client/dist/graphql-client/dist/graphql-client/http-fetch.mjs:40:19)"."

**Comment by matteodepalo** [comment]
@julianCast thank you for opening the issue, it seems like you figured out that adding `await` fixes it.
