### ISSUE TITLE
shopify.session.getCurrentId() fails to read request headers from Next.js app router

### ISSUE THREAD

**Issue by artooras** [Shopify/shopify-api-js#1265]
# Issue summary

I'm using Next.js 14 (but this applies from 13 onwards) for building an embedded Shopify App. Before migrating to the app router, in my pages/api route I had the following code which was working fine:

```
export default async function handler(req: NextApiRequest) {
  [...] 
  const sessionId = await shopify.session.getCurrentId({
    isOnline: false,
    rawRequest: req
  })
  [...]
}
```

Once I migrated to the the app router, I now have a route.ts file in which I execute similar code:

```
export async function POST(req: Request) {
  [...]
  const sessionId = await shopify.session.getCurrentId({
    isOnline: false,
    rawRequest: req
  })
  [...]
}
```

but this time, instead of a valid `sessionId`, I get an error saying `[shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: false}`. Now, the header is actually there, which I am able to access through:

`console.log(req.headers.get('Authorization'))`

which outputs

`Bearer MY_SESSION_TOKEN`

However, as the `shopify.session.getCurrentId` suggests, it expects a `rawRequest`, while in the `route.ts` the instance of the `req` is that of `NextRequest`. And somehow the shopify function is not able to access the headers properly.

What is the specific request format that the shopify library expects? And how I can convert the NextRequest into that format?

Thanks!

- `@shopify/shopify-api` version: ^9.3.2
- Node version: v20.11.1
- Operating system: macOS 14.3 (Sonoma)

## Expected behavior

The request should be recognized as valid as it contains the authorization header.

## Actual behavior

The shopify library fails to read the headers properly.

**Comment by ozzyonfire** [comment]
have you tried the web-api methods? Your api route is getting a NextApiRequest which is just an extension of the native Request object. 

This should be compatible with the web-api. I have an example repo with next js app router, verified sessions and hitting a protected api route. It also uses the old AppBridge, but I'm currently working on migrating it to the new one. 

https://github.com/ozzyonfire/shopify-next-app
