### ISSUE TITLE
please upgrade to node-fetch 3.x

### ISSUE THREAD

**Issue by mariusa** [Shopify/shopify-api-js#280]
https://github.com/Shopify/shopify-node-api/blob/2430848203ed3605e91763be652e7b1f8f37b52a/package.json#L48

The latest version is 3.x, with the major change being that only ESM `import` is possible now.
This library already uses it via `import`, so it should just work:
https://github.com/Shopify/shopify-node-api/blob/c9d94515773745ebd89be226bb6ebab244cf1e62/src/clients/http_client/http_client.ts#L5

**Comment by tbeseda** [comment]
Additionally, the installed version has a _high_ severity vulnerability https://github.com/advisories/GHSA-r683-j2x4-v87g

**Comment by mariusa** [comment]
still valid

**Comment by mariusa** [comment]
not stale
