### ISSUE TITLE
Can't build the @shopify/shopify-api on Vite and Parcel

### ISSUE THREAD

**Issue by sorcamarian** [Shopify/shopify-api-js#302]
# Issue summary
I tried to build a simple example where the Shopify API calls the "shop.myshopify.com/admin/api/2022-01/customers.json" endpoint.
I wanted to see where they put the _API Key when making the HTTP Request_ so I can use a code on the Front End and POST a new customer.

The code that I use:

```
import Shopify from '@shopify/shopify-api';

const client = new Shopify.Clients.Rest('https://SHOP.myshopify.com/', "API KEY");

const data = await client.get({
  path: 'customers',
});
console.log(data);
```

In both Vite and Parcel builders I get an error.

**Error in Vite**:
`Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (@shopify_shopify-api.js:1892:17)
    at __require2 (@shopify_shopify-api.js:19:50)
    at node_modules/jws/lib/sign-stream.js (@shopify_shopify-api.js:2448:19)
    at __require2 (@shopify_shopify-api.js:19:50)
    at node_modules/jws/index.js (@shopify_shopify-api.js:2628:22)
    at __require2 (@shopify_shopify-api.js:19:50)
    at node_modules/jsonwebtoken/decode.js (@shopify_shopify-api.js:2661:15)
    at __require2 (@shopify_shopify-api.js:19:50)
    at node_modules/jsonwebtoken/index.js (@shopify_shopify-api.js:4719:15)
    at __require2 (@shopify_shopify-api.js:19:50)`
<img width="1440" alt="Screenshot 2022-02-12 at 02 59 21" src="https://user-images.githubusercontent.com/12509753/153689660-324c70be-e9dd-4210-95bb-1ca2e24795d0.png">
<img width="1440" alt="Screenshot 2022-02-12 at 02 58 52" src="https://user-images.githubusercontent.com/12509753/153689635-4a0aeae0-3653-4a1f-b557-78cedd0849ec.png">

**Errors in Parcel**
```
@parcel/core: Failed to resolve 'buffer' from './node_modules/@shopify/shopify-api/dist/utils/safe-compare.js'
/Users/mariansorca/Documents/2022/January/Quick turn on Custom CSS for Shopify/theme_export__bay-area-skin-care-company-myshopify-com-dawn__26JAN2022-1257pm/node/parcel-builder/node_modules/@shopify/shopify-api/dist/utils/safe-compare.js:17:21
  16 |         if (typeof strA === 'object' && typeof strB === 'object') {
> 17 |             buffA = Buffer.from(JSON.stringify(strA));
>    |                     ^^^^^^
  18 |             buffB = Buffer.from(JSON.stringify(strB));
  19 | 
```
<img width="1440" alt="Screenshot 2022-02-12 at 03 04 04" src="https://user-images.githubusercontent.com/12509753/153689884-fceeccf6-4c13-4dcc-b8fe-819d426e4a71.png">

I'm using Node v16.13.0

**Comment by KingGilbert89** [comment]
I have the same error.
Have you been able to find a solution in the meantime?

**Comment by sorcamarian** [comment]
I think it’s because the code if only for the backend

**Comment by cquemin** [comment]
Yes it is indeed a library for javascript/typescript based backend. So you would need to use this library on a javascript/typescript backend and you would then call those endpoints and any other you add from your frontend.
We have recently released v6 of this API with some easy integration with express and we have also made it easy to chose your own session storage with same ready to use example.
