### ISSUE TITLE
Add ability to specify fields more narrowly

### ISSUE THREAD

**Issue by jakeleventhal** [Shopify/shopify-api-js#342]
## Overview

A lot of API endpoints have a parameter `fields` to specify which fields should be returned. There should be the ability to drill down to sub fields. For instances products.json has a field called `variants` which is an array of product variants. You should be able to do `{fields: 'variants.id'}` and just get the following returned:
```json
[
  {"variants": [{"id": 1}, {"id": 2}]},
  {"variants": [{"id": 3}]}
]
```

## Type

- [x] New feature
- [x] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

It is annoying fetching way more data than needed

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [x] I have described this feature request in a way that is actionable (if possible)

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by mkevinosullivan** [comment]
This is not a limitation of the library.  The underlying REST API provided by the Shopify system itself doesn't support that level of sub-field granularity.

To direct this feedback to the team supporting, say, `Products`, please use the "Was this section helpful?" feedback mechanism under the **Parameters** section of [Retrieve a single product](https://shopify.dev/docs/api/admin-rest/2023-01/resources/product#get-products-product-id) - that feedback mechanism directs a GitHub issue to the appropriate team for their review.
