### ISSUE TITLE
Webhook failed with error code 403 caused by hmac validation

### ISSUE THREAD

**Issue by emmajxli** [Shopify/shopify-api-js#354]
# Issue summary
A partner submitted a ticket for the issue for one of their orders/fulfilled webhook. This webhook usually get 100 orders fulfilled everyday within 1 or 2 hours. Most of the orders work properly, but a small number of orders failing with an error code of 403.

The error message is: Could not validate request for topic orders/fulfilled. In the last 4h, 8.9% of the webhook delivered returns this 403 error. 

Looking at the code that returns this error, it can be seen that this is due to hmac validation failing: https://github.com/Shopify/shopify-node-api/blob/e451ab91e7e64ae191c63ff953eb3f0e88431d2a/src/webhooks/registry.ts#L387-L416

However, the hmac header value originates from Shopify when calling our webhook - hence this validation should never fail. So either the calling side or the validation side is not 100% bulletproof - in other words for certain orders, the code is not working correctly. 

## Expected behavior

The error should not show up. 

## Actual behavior

I had a discussion with our webhook developer Marcus, and he confirmed that he has chatted with the partner, the webhook failed to validate 11 times, and then succeed on the 12th attempt. He also checked and discussed this issue with team but still cannot has the answer for why this would happened. 

Other useful resource: 

[Shopify community post for this post](https://community.shopify.com/c/shopify-apis-and-sdks/webhook-hmac-validation-failing-in-shopify-shopify-api/m-p/1533472#M78564)
[Ticket submitted by the partner](https://adequate-desk.shopify.io/tickets/29699715)

If any additional info needed, please contact me via slack: Emma Li

## Steps to reproduce the problem

N/A

## Reduced test case

N/A

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by haveneersrobin** [comment]
Are there any updates regarding this? I am getting 401s for my application in 'some' shops and for 'some' webhook calls.. So it is very much not consistent. This is quite frustrating as our webhooks are now getting deleted. 

Could this have to do with too many requests in a short period of time? Would batching/queueing them help?

**Comment by mariusa** [comment]
> Could this have to do with too many requests in a short period of time? Would batching/queueing them help?

No, this always happens on some products, in some cases. I was able to replicate, but ignored by Shopify. There's is an issue with Shopify validation code.

**Comment by juhanaka** [comment]
I have the same issue with the `orders/fulfilled` topic returning 403 seemingly randomly. All other webhook topics work and `orders/fulfilled` works 99% of the time. It very much seems to be something in how the Shopify node library handles the request or how the requests are sent from Shopify on this particular topic.

**Comment by thecodepixi** [comment]
@haveneersrobin Hey, please do not tag Shopify employees directly in these threads. These are always on our radar so someone will follow up when/if appropriate. Additionally, I am no longer on the team that manages and contributes our API libraries, so I'm not in a position to assist with this. Take care ✌🏻
