### ISSUE TITLE
AssignedFulfillmentOrder.all() Always Returns an Empty Array

### ISSUE THREAD

**Issue by jaret32** [Shopify/shopify-api-js#368]
# Issue summary

The `AssignedFulfillmentOrder.all` method is returning an empty array even though there are fulfillment orders assigned to the app that is making the call. I have verified that the following two examples are producing different results given the same inputs using API version 2022-04.

```javascript
const session = await Shopify.Utils.loadOfflineSession(shop);
const fulfillmentOrders = await AssignedFulfillmentOrder.all({ session, assignment_status: 'fulfillment_requested' });
// fulfillmentOrders is empty
```

```javascript
const session = await Shopify.Utils.loadOfflineSession(shop);
const client = new Shopify.Clients.Rest(session.shop, session.accessToken);
const response = await client.get({
  path: 'assigned_fulfillment_orders',
  query: { assignment_status: 'fulfillment_requested' }
});
// response.body.fulfillment_orders is not empty
```

The issue is that neither the `NAME` or `PLURAL_NAME` fields of the `AssignedFulfillmentOrder` class match the 'fulfillment_orders' field in the response body. The applicable code can be found in the `Base.createInstancesFromResponse()` method [here](https://github.com/Shopify/shopify-node-api/blob/9297dda7da2c266b9987d65cba693abbe7ab176a/src/base-rest-resource.ts#L210). To fix this you could just change the `NAME` and `PLURAL_NAME` fields to 'fulfillment_order' and 'fulfillment_orders' respectively.

## Expected behavior

The method should return the matching resources.

## Actual behavior

The method returns an empty array.

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Sorry the delay in responding here folks. You're absolutely right and we had an bug in that class. It's been fixed now!
