### ISSUE TITLE
proposal: bump node-fetch version => 3.2.4

### ISSUE THREAD

**Issue by michealroberts** [Shopify/shopify-api-js#378]
## Overview/summary

I'm currently running into some legacy issues when utilise this package with an ES modules build.

I'm wondering if we could upgrade node-fetch to version `"node-fetch": "^3.2.4"` to be on parity with similar packages...?

## Motivation

> What inspired this enhancement?

I'm currently attempting to utilise this library within a Nuxt 3 project, and also a Next.js project. Both projects are failing on build when attempting to place this on the edge.

## Checklist

- [X] I have described this enhancement in a way that is actionable (if possible)

**Comment by mariusa** [comment]
still applicable to v6

**Comment by mariusa** [comment]
not stale & easy fix
