### ISSUE TITLE
How to "un-register" a webhook

### ISSUE THREAD

**Issue by doneumark** [Shopify/shopify-api-js#480]
The docs doesn't mention anything about it, but it seems pretty basic to me, that in some point you would like to remove a webhooks from a shop.
Or, having somekind of "opposite" action to the `Shopify.Webhooks.Registry.register` function.
Is there such a way? or how should we handle those scenarios?

**Comment by daviareias** [comment]
I'm also really curious about this, been playing with webhooks and I get hundred of emails after I stop my test server. I hope there's no negative consequence to let them expire.

**Comment by wisniewski94** [comment]
Not possible at the moment. You need to write your own deletion logic https://stackoverflow.com/a/23631865/6110804

However, it would be nice to call Shopify.Webhooks.Registry.unregisterAll()

**Comment by egillanton** [comment]
@doneumark I support this ticket. 👍🏻 

I my case, I created an app with a custom authentication page, I don't want to register the webhooks on installation, I prefer doing it on successful authentication. The same applies when the user logs out from the app and does not uninstall the app completely, I want to be able to un-register or delete the webhook for that store.

**Comment by daviareias** [comment]
I'm reading the code right now and it seems that not only the webhook keeps registered on Shopify, but also after the customer uninstalls the app, his "WebhookRegistryEntry" keeps stored inside the app, and is never deleted.

Doesn't this lead to memory leaks?

**Comment by egillanton** [comment]
I created a helper function written in js.
This function retrieves the webhook for the topic, ORDERS_PAID, ORDERS_FULFILLED and then delete them.
Note, that _first_ and _topic_ parameters in _webhookSubscriptions_ are hardcoded for now, feel free to edit.

Also, I have no idea if _first_ should be the exact number of topics, because _Shopify.Webhooks.Registry.register_ and _Shopify.Webhooks.Registry.registerAll_ prevent multiple webhooks created for the same topic if I understand it correctly.

```javascript
export const unregisterWebhooks = (session) => {
	return new Promise(async (resolve, reject) => {
	  try {
		const client = new Shopify.Clients.Graphql(
		  session.shop,
		  session.accessToken
		);
  
		// Retrieve the webhook for the topic
		const getWebhooksResponse = await client
		  .query({
			data: `{
			webhookSubscriptions(first: 10, topics: [ORDERS_PAID, ORDERS_FULFILLED]) { // <--- TODO: This is hardcoded, should be passed in as a parameter
			  edges {
				node {
				  id,
				  topic
				}
			  }
			}
		  }`,
		  })
		  .catch((error) => {
			console.log(error);
		  });
  
		if (getWebhooksResponse) {
		  for (const webhook of getWebhooksResponse.body.data.webhookSubscriptions.edges) {
			console.log(`Unregistering webhook: with id: ${webhook.node.id} and topic: ${webhook.node.topic}`);
			// Delete the webhook
			const deleteWebhookResponse = await client
			  .query({
				data: `mutation {
				  webhookSubscriptionDelete(id: "${webhook.node.id}") {
					deletedWebhookSubscriptionId
					userErrors {
					  field
					  message
					}
				  }
				}`,
			  })
			  .catch((error) => {
				console.log(error);
			  });
  
			if (deleteWebhookResponse) {
			  if(deleteWebhookResponse.body.data.webhookSubscriptionDelete.userErrors.length > 0) {
				console.log(`Failed to unregister webhook: with id: ${webhook.node.id} and topic: ${webhook.node.topic} for shop: ${session.shop}`);
				console.log("webhookSubscriptionDelete.userErrors:");
				for (const userError of deleteWebhookResponse.body.data.webhookSubscriptionDelete.userErrors) {
				  console.log(`\tField: ${userError.field}\tMessage: ${userError.message}`);
				}
			  }else{
				console.log(
				  `Successfully unregistered webhook: with id: ${webhook.node.id} and topic: ${webhook.node.topic} for shop: ${session.shop}`
				);
			  }
			}
		  }
		}
		resolve();
	  } catch (error) {
		reject(error);
	  }
	});
  };
  ```

**Comment by paulomarg** [comment]
Hey folks, thanks for this! Starting in v6, the way we register webhooks has changed: we now go over the configured handlers, and make sure that they are the final set created for the app - so it will add, delete or update handlers as necessary.

Please see the [webhooks guide](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/webhooks.md) for more information on setting up handlers with the new version.

**Comment by rohanvermawork** [comment]
@molotow11 You can also do the same with GraphQL also 
https://shopify.dev/docs/api/admin-graphql/2023-04/mutations/webhookSubscriptionDelete

**Comment by molotow11** [comment]
Sorry, it was a question about how to use `Shopify.Webhooks.Registry` not calling API directly.
