### ISSUE TITLE
Add support for metafieldNamespaces on Webhook.Registery.Register

### ISSUE THREAD

**Issue by gil--** [Shopify/shopify-api-js#495]
## Overview

Add support for the metafieldNamespaces when registering a webhook

## Type

- [X] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

Trying to retrieve a metafield added via checkout extensions to the order.

**Comment by StefanoDiLegami** [comment]
It would also be nice to have the [includeFields](https://shopify.dev/api/admin-graphql/2022-10/input-objects/WebhookSubscriptionInput#field-webhooksubscriptioninput-includefields) option beside [metafieldNamespaces](https://shopify.dev/api/admin-graphql/2022-10/input-objects/WebhookSubscriptionInput#field-webhooksubscriptioninput-metafieldnamespaces), so we can receive additional fields in our webhooks.

**Comment by mariusa** [comment]
+1. It's impossible now to configure webhooks to include metafields.

**Comment by paulomarg** [comment]
Hey folks, thanks for reporting this. We've introduced the ability to set this and other fields when creating webhooks in v6!

Please see the [`shopify.webhooks.addHandlers` documentation](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/webhooks/addHandlers.md) for more details.
