### ISSUE TITLE
Types in order and product dont match the real world rest api and miss clarity in some cases

### ISSUE THREAD

**Issue by flowluap** [Shopify/shopify-api-js#532]
# Issue summary
I am currently implementing the types of this library into our codebase. Before this we had our own types mirrored.
I miss some clarity in certain types and I think some of them do not represent the actual status quo of REST API responses.

## Expected behavior
The [ProductType](https://github.com/Shopify/shopify-api-node/blob/main/src/rest-resources/2022-07/product.ts) has Variants represented as:
```
 public variants: Variant[] | null | {[key: string]: any};
```
But shouldn't it only be, as a product will always have a default variant at least assigned?
```
 public variants: Variant[];
```

# Another example:
[Order line_items](https://github.com/Shopify/shopify-api-node/blob/main/src/rest-resources/2022-07/order.ts) are currently represented as this.
```
    line_items: {
        [key: string]: unknown;
    }[] | null;
```
But in our codebase we had it as follows:
```
export class ShopifyOrderFulfillmentLineItemType {
    public id!: number;
    public variant_id!: number;
    public quantity!: number;
    public fulfillment_status?: string;
}

```

# Are there any plans on working out the types here and can I help with this?

**Comment by citrus** [comment]
+1 on this.
