### ISSUE TITLE
Validating the timestamp value during oauth

### ISSUE THREAD

**Issue by clement911** [Shopify/shopify-api-js#570]
When OAuth occurs, the server must validate that the HMAC matches.

That's fine, but what about the timestamp? Shouldn't there be some validation to check that the timestamp parameter is within some certain tolerance threshold to avoid someone trying to reuse a valid HMAC (found in some logs for example)?

**Comment by clement911** [comment]
Can we please get a reply on this topic?
This seems like a potential security issue.

**Comment by clement911** [comment]
Hello? I was under the impression that Shopify paid a lot of attention to security?

**Comment by cquemin** [comment]
@clement911 Thanks for raising this. We are looking into this!

**Comment by clement911** [comment]
@cquemin any updates?
