### ISSUE TITLE
verify-request.js:25:18:  TypeError: session?.isActive is not a function

### ISSUE THREAD

**Issue by valorloff** [Shopify/shopify-api-js#573]
# Issue summary
After migrating existing app from old koa/next approach to shopify-create-app, stopped working customSessionStorage in verify-request.js:25:18: `if (session?.isActive()) {` condition.

`TypeError: session?.isActive is not a function`

if we look at the session object, it don't have any isActive function
```
┃{
┃   id: 'xxxx.myshopify.com_66922237753',
┃   shop: 'xxxx.myshopify.com',
┃   state: '361444000477369',
┃   isOnline: true,
┃   accessToken: 'shpat_51721a758889a54a62c85f3asdfd73059',
┃   onlineAccessInfo: {
┃     account_number: 0,
┃     associated_user: {
┃       account_owner: true,
┃       collaborator: false,
┃       email: 'xxx@dxxxa.com',
┃       email_verified: true,
┃       first_name: 'xxxery',
┃       id: 66666537753,
┃       last_name: 'xxxff',
┃       locale: 'en-US'
┃     },
┃     associated_user_scope: 'write_products,write_themes,write_script_tags',
┃     expires_in: 866698,
┃     session: 'dfa4a197ad0c077708ae212f1db820a0f333545eaeb4866dc888efe477792fe6'
┃   },
┃   scope: 'write_products,write_themes,write_script_tags',
┃   expires: 2022-10-22T23:33:58.597Z
┃ }
```
Can you help please ?

**Comment by tolgap** [comment]
If you are using a Session Storage that stores sessions as JSON strings, and then deserializes them, you will lose any functions of your Session.

**Comment by bluedge** [comment]
I encountered the same bug with isOnline: true
The problem is not the custom storage method but a bug in the Session Class form Shopify.

The issue is in the `Session` class, line 82.
it reads:
```
if (scopesUnchanged &&
         this.accessToken &&
         (!this.expires || this.expires >= new Date())) {
         return true;
}
```
it should be:
```
if (scopesUnchanged &&
         this.accessToken &&
         (!this.expires || new Date(this.expires) >= new Date())) {
         return true;
}
```

**Note**: One should return an instance of Shopify `Session` class to be able ti use the method `isActive(...)`

**Comment by mkevinosullivan** [comment]
How are you serializing and deserializing Sessions to/from your custom storage?

In `v6`, there is a `Session` instance method `.toPropertyArray` to serialize and a class method `Session.fromPropertyArray` to deserialize.

Prior to the return of `.fromPropertyArray`, there's the following [line of code](https://github.com/Shopify/shopify-api-js/blob/main/lib/session/session.ts#L74)
```js
Object.setPrototypeOf(obj, Session.prototype);
```
which should ensure the return object is a `Session` and therefore have `isActive()` as part of it.

If `.fromPropertyArray` is not being used, would recommend adding that line to whatever conversion method being used to convert stored session data back into a `Session` object.

@bluedge w.r.t. your comment, if `Session.fromPropertyArray` is being used to deserialize, then [these lines](https://github.com/Shopify/shopify-api-js/blob/main/lib/session/session.ts#L58-L59) will have converted the raw `expires` number back into a `Date` object.

**Comment by SaeedYasin** [comment]
@mkevinosullivan using `.toPropertyArray` on `Session` instance to serialize and then using class method of `Session.fromPropertyArray` to deserialize solved the issue for me. Thank you. 😄

**Comment by Iciren93** [comment]
Hi guys, anybody solved this issue? I am having the same problem implementing custom session storage with firebase or firestore. Anybody can shed more info on this .toPropertyArray .fromPropertyArray?

**Comment by SaeedYasin** [comment]
> 

@Iciren93 yes, please refer to this code for an example how to solve this issue, https://github.com/SaeedYasin/shopify-app-template-node/blob/main/web/backend/prisma/database/sessions.ts#L49

**Comment by joantune** [comment]
> How are you serializing and deserializing Sessions to/from your custom storage?
> 
> In `v6`, there is a `Session` instance method `.toPropertyArray` to serialize and a class method `Session.fromPropertyArray` to deserialize.
> 
> Prior to the return of `.fromPropertyArray`, there's the following [line of code](https://github.com/Shopify/shopify-api-js/blob/main/lib/session/session.ts#L74)
> 
> ```js
> Object.setPrototypeOf(obj, Session.prototype);
> ```
> 
> which should ensure the return object is a `Session` and therefore have `isActive()` as part of it.
> 
> If `.fromPropertyArray` is not being used, would recommend adding that line to whatever conversion method being used to convert stored session data back into a `Session` object.
> 
> @bluedge w.r.t. your comment, if `Session.fromPropertyArray` is being used to deserialize, then [these lines](https://github.com/Shopify/shopify-api-js/blob/main/lib/session/session.ts#L58-L59) will have converted the raw `expires` number back into a `Date` object.

that did it of course!

would be even better if we had a mention of that in the documentation here:

https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-session-storage/implementing-session-storage.md

:)

and/or a link on that one to here: https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/session-storage.md

and I would say either in one or another (or both) make this part more salient
