### ISSUE TITLE
Need more detail example for the Express js session stoage 

### ISSUE THREAD

**Issue by Sky-bits** [Shopify/shopify-api-js#584]
## Overview/summary
express js server where too get the active shop?
...

## Motivation

> What inspired this enhancement?
need complete example 
...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue
Set up Context in **express**   https://github.com/Shopify/shopify-api-node/blob/main/docs/getting_started.md
---

## Checklist

- [ ] I have described this enhancement in a way that is actionable (if possible)
need detail example

**Comment by cquemin** [comment]
Quite a few implementations for session storage can be found [here](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-session-storage) as well as a dedicated package that makes it easy to integrate with express in the same repo over [here](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-express)
