### ISSUE TITLE
v6 session expires seconds vs. milliseconds design

### ISSUE THREAD

**Issue by deldrid1** [Shopify/shopify-api-js#603]
## Overview

Working through moving from `v6.0.0-rc5` -> `v6.0.0-rc9` and found some unexpected behavior looking at the docs + bugs upon additional unit testing / code review.

It's only barely mentioned in two places but under certain circumstances `session.expres` is in **epoch seconds** rather than JavaScript standard epoch **milli*seconds:
- https://github.com/Shopify/shopify-api-node/blob/6c427af71eaaffe7cf1db4de27731238bf19aaa9/docs/usage/session-storage.md?plain=1#L100
- https://github.com/Shopify/shopify-api-node/blob/6c427af71eaaffe7cf1db4de27731238bf19aaa9/docs/usage/session-storage.md?plain=1#L141

If this was expecting `(new Date()).getTime()` milliseconds like the rest of the JS world, there would be a lot fewer bugs and confused developers I suspect, plus a lot less `*1000` / `Math.round(/1000)` in `SessionStorage`s

Where this bites particularly hard is in `Session.fromPropertyArray`, which doesn't do any kind of validation and can lead to some seriously egregious expiration times in the future...
...

## Type

- [ ] New feature
- [X] Changes to existing features

**Comment by cquemin** [comment]
This has been fixed by the above-mentioned PR above.
