### ISSUE TITLE
Importing @shopify/shopify-api in NextJS middleware throws "Can't resolve 'fs'" error

### ISSUE THREAD

**Issue by bhaskarmurthy** [Shopify/shopify-api-js#605]
# Issue summary

I'm using Vercel's middleware feature to set up app authentication / redirects etc (similar to the express example in the nodejs app template).

Every time the function is executed, I get an error "**Can't resolve 'fs'**" - which I believe is due to the sqlite dependency.
I've set up the configuration to _not_ use SQLite, but it looks like the import is still being executed.

```
import { Shopify, LATEST_API_VERSION } from "@shopify/shopify-api";

...

Shopify.Context.initialize({
  API_KEY: process.env.SHOPIFY_API_KEY,
  API_SECRET_KEY: process.env.SHOPIFY_API_SECRET_KEY,
  SCOPES: process.env.SHOPIFY_SCOPES.split(","),
  HOST_NAME: process.env.HOST.replace(/https?:\/\//, ""),
  HOST_SCHEME: process.env.HOST.split("://")[0],
  API_VERSION: LATEST_API_VERSION,
  IS_EMBEDDED_APP: true,
  SESSION_STORAGE: new Shopify.Session.MemorySessionStorage(),
});
```

```
error - ../../node_modules/@mapbox/node-pre-gyp/lib/clean.js:8:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
../../node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
../../node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
../../node_modules/sqlite3/lib/sqlite3-binding.js
../../node_modules/sqlite3/lib/sqlite3.js
../../node_modules/@shopify/shopify-api/dist/auth/session/storage/sqlite.js
../../node_modules/@shopify/shopify-api/dist/context.js
../../node_modules/@shopify/shopify-api/dist/index.js
./src/middleware.ts
```

The root cause of the error seems to be an import in `context.js`, where sqlite is imported _regardless_ of whether session storage is using SQLite or not.

```
var sqlite_1 = require("./auth/session/storage/sqlite");
```

## Expected behavior

SQLite (and subsequently, `fs`) should not be imported if SQLite is not used for session storage.

## Actual behavior

Runtime error is thrown - Module not found: Can't resolve 'fs'

<details>
```
error - ../../node_modules/@mapbox/node-pre-gyp/lib/clean.js:8:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
../../node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
../../node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
../../node_modules/sqlite3/lib/sqlite3-binding.js
../../node_modules/sqlite3/lib/sqlite3.js
../../node_modules/@shopify/shopify-api/dist/auth/session/storage/sqlite.js
../../node_modules/@shopify/shopify-api/dist/context.js
../../node_modules/@shopify/shopify-api/dist/index.js
./src/middleware.ts
```
</details>

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://webkit.org/test-case-reduction/).

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hi folks! We've recently released v6 of this package, which no longer requires any database packages to be installed (they're all separate packages now).

We've made some big improvements to the library with that update, so we created a [migration guide](https://github.com/Shopify/shopify-api-js/blob/main/docs/migrating-to-v6.md) that should help you upgrade your app.

I'll close this issue since upgrading to the latest version will solve the issue for folks not using sqlite, but please reopen / open new ones if you still have problems.
