### ISSUE TITLE
Ngork hasn't been available for at least two days

### ISSUE THREAD

**Issue by janis-rasins-accenture** [Shopify/shopify-api-js#608]
# Issue summary

Ngork hasn't been available for at least two days. It looks like they've been hacked. If of course the service worked before. 

## Expected behavior

Try to open [https://ngrok.com/](https://ngrok.com/) and get a token

## Actual behavior

Ngork redirect me to a scam news feed.

## What would I like?

To start a develop. Is there a way to start develop without an ngork token?

**Comment by cquemin** [comment]
Must have been temporary, I have been using it today without any problem
