### ISSUE TITLE
413 Request Entity Too Large" Shopify blocking requests over 3MB?

### ISSUE THREAD

**Issue by lamark-Alba** [Shopify/shopify-api-js#616]
Issue summary
Shopify is blocking any requests over 3 MB to my server.
Write a short description of the issue here ↓
Whenever I post mulipart/form-data over 3 MB shopify blocks my request.

It looks like nginx is blocking my request which is weird since I'm not using nginx anywhere in my application. The request is stopped before it reaches my Koa backend.

Here is a photo of the response from the server:
response (2)

Expected behavior
What do you think should happen?

Receive my request on the backend

Actual behavior
What actually happens?

I receive an error:
Error: Request failed with status code 413

Here is the response from the server:
res

Steps to reproduce the problem
Append images over 3 MB to multipart/form-data
Post request to server using axios
Reduced test case
The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

Checklist
[ X ] I have described this issue in a way that is actionable (if possible)

**Comment by gfr2003** [comment]
Hey @noahbaron91, thanks for your question - as far as I know, Shopify does not limit POSTs to 1MB, but if your app is running on nginx, you may be running into its default limit: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

Unfortunately there's not much else I can think of that might be causing this, but it doesn't look like this particular issue is happening on Shopify's side. I'll go ahead and close it, but please feel free to reopen / report another issue if you run into any problems on our side of things.

**Comment by cquemin** [comment]
I am not too sure I understand correctly @lamark-Alba .
Couple of questions for me:

- What is the shopify end point you are trying to hit ? Or where does the shopify call come from?
- On which method of the library do you see this error occurring?
- Can you also add the stacktrace?
- You're saying you're not receiving the request on your backend, where is your backend located ? locally on your dev machine? Is it deployed on a cloud provider?
