### ISSUE TITLE
can't use v6 with Fastify anymore due to webhooks processing

### ISSUE THREAD

**Issue by mariusa** [Shopify/shopify-api-js#624]
# Issue summary

Shopify webhook processing also sends headers, which messes up non-Express frameworks, such as Fastify.

In previous version, 
https://github.com/Shopify/shopify-api-js/blob/main/docs/migrating-to-v6.md#changes-to-webhook-functions
this was workaround-able with a custom handler ran very early, before body was received
```
await Shopify.Webhooks.Registry.process(req.raw, res.raw);
```
`process()` was fetching request body, and sending response headers, so it handled everything.

In v6, it wants the rawbody though, already handled by the app:
```
await shopify.webhooks.process({
      rawBody: (req as any).rawBody, // as a string
      rawRequest: req,
      rawResponse: res,
    });
```
This is good.
BUT it also sends HTTP headers/responses. 
If we wait until body is received by our app, processing webhooks with above leads to error ` FastifyError: Reply was already sent.`

## Expected behavior

Since `process()` has stopped reading body by itself, also stop sending HTTP traffic. Just process the data and return headers/status to the caller app, which will handle them using any framework.

## Steps to reproduce the problem

1. try to implement webhook handlers using Fastify instead of Express

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hi, thanks for reporting this! As you mentioned, the new `process` call will always respond to Shopify, whether it worked or not.

Is there a specific use case for _not_ responding once we run the handler? The idea behind this method is that you can call it, it'll trigger your added handler and make sure Shopify gets a response, so the app doesn't have to worry about dealing with the request.

We could look into optionally skipping the response part, but I'd like to understand the scenario a bit better.
