### ISSUE TITLE
Make authenticated request from proxy: Missing Authorization header

### ISSUE THREAD

**Issue by valorloff** [Shopify/shopify-api-js#632]
# Issue summary
Hi!
Thanks for the abolition customSessionStorage and switching to shop name identification!
But after migrate to useAppQuery and  api-js-V.6, it is not clear where to get the sessionId for making requests, coming from the App proxy.
     
```
app.get('/api/proxy_shopify', async (req, res) => {
    await redirectToAuth(req, res, app);

    const sessionId = await shopify.session.getCurrentId({
      rawRequest: req,
      rawResponse: res,
      isOnline: true,
    });
.............................
```
i get
`[shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: false}`

## Expected behavior
I was sure that the incoming request headers should contain the necessary session object for requests

## Steps to reproduce the problem
When requests are received to app proxy url, request data don't contain valid authenticated data, that is contained when a request is received from internal useAppQuery (with authanticatedFetch) request

## Question
How can valid session data from app proxy be obtained?

**Comment by valorloff** [comment]
Hi!
I got offline sessionId by 
`shopify.session.getOfflineId(req.query.shop);`
and now I can make requests
is it correct way?

**Comment by valorloff** [comment]
Unfortunately In production 
`shopify.session.getOfflineId(req.query.shop);`
don't works.
Please, what is correct way to make auth requests during incoming requests from App proxy ?

**Comment by timmatheson** [comment]
I am also getting this exact same behavior with Shopify Flow triggers.
Even after scaffolding a stock extension from the shopify-cli generators.
All inbound requests loose the shop parameter and go to /auth please help!

**Comment by valorloff** [comment]
in shopify apps docs specified proxy URL:
```
GET /apps/awesome_reviews/extra/path/components?extra=1&extra=2 HTTP/1.1
  Host: shop-domain.com
  Cookie: csrftoken=01234456789abcdef0123456789abcde;
  _session_id=1234456789abcdef0123456789abcdef;
  _secure_session_id=234456789abcdef0123456789abcdef0

```
i see there _session_id, possible this is desired sessionId, needed for
`sqliteSessionStorage.loadSession(sessionId);`
?

**Comment by valorloff** [comment]
if you try
```
shopify.auth.callback({
        rawRequest: req,
        rawResponse: res,
      });
```
i get
`CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop`

due they are disabled in app proxy request!
So, please, how to make authenticated request from app proxy?

**Comment by brdsmth** [comment]
I am experiencing the same issue. When I hardcode the `sessionId` inside `validate-authenticated-session.js` in the `shopify.validateAuthenticatedSession()` middleware I get the correct expected behavior. 

I created my app one day ago with the most updated node app in the `shopify-cli` and am following the documentation. I am making a request to my app via postman to a custom api route behind the `app.use('/api/*, shopify.validateAuthenticatedSession())` middleware. I installed my app on a test store and successfully created a session via `MongoDBSessionStorage` and saved the session to the database. 

Inside `validateAuthenticatedSession()` there's a `try / catch` block calling `api.session.getCurrentId()` with the `req, res, isOnline` as input parameters. This was not working for me until I hardcoded my test store's `sessionId` and now it works. I'm not sure if this is an issue with `validateAuthenticatedSession()` or the `MongoDBSessionStorage` library. 

The below `try / catch` block works as intended (hardcoded) but does not work out-of-the-box when making request from postman with this url: 

`GET {{ shopify_provided_ngrok_url }}/api/{{ custom_route }}?shop=my-shop.myshopify.com`

```
try {
        sessionId = await api.session.getCurrentId({
          isOnline: config.useOnlineTokens,
          rawRequest: req,
          rawResponse: res
        });
        sessionId = 'offline_my-shop.myshopify.com'
      } catch (error) {
        await config.logger.error(`Error when loading session from storage: ${error}`);
        await handleSessionError(req, res, error);
        return undefined;
      }
 ```

**Comment by brdsmth** [comment]
It looks like the most recent version of the node app included in the `shopify-cli` already has some middleware for parsing out the shop parameter, so I wasn't using that line you mentioned (though maybe I should be?). 

Out of the box the node app template has this line 

`app.use("/api/*", shopify.validateAuthenticatedSession());` 

And I just set up a router for `*/api/health` to see if my external requests were getting authenticated correctly with that middleware function, and they were not. So I dug into the `shopify.validateAuthenticatedSession()` library function in the `@shopify/shopify-app-express` package. It looks like the line 

```
sessionId = await api.session.getCurrentId({
          isOnline: config.useOnlineTokens,
          rawRequest: req,
          rawResponse: res
        });
```

is not reading my shop parameter from the req correctly (`sessionId` was returning `null`), so I hardcoded it and things worked. I could have something wrong as I'm somewhat new to developing shopify apps.

**Comment by dongido001** [comment]
Hi @valorloff,

Could you let me know if you managed to get this fixed?

I am facing similar issue. But I think for a request to be passed through app proxy, it's endpoint has to start with "/apps/*"

but you are using /api/*, did it work?

**Comment by valorloff** [comment]
you messed up everything, you need to specify the correct url in the fetch:
`fetch(`/apps/proxy/api/proxy_shopify?......`

**Comment by dongido001** [comment]
thanks you @valorloff

**Comment by valorloff** [comment]
@brdsmth  you need use the /api endpoint, the request come to, which is contain shop name, which is use for session_id, which is use for getting session from storage

**Comment by Paula-Alohas** [comment]
Hi @valorloff Thank you for your help. If I do that then I receive a response saying I am missing the Authorization header. Am I missing something else? the validateAuthentication already is implemented with all the process inside the middleware. I cannot choose to get the Id by findSessionsByShop....Obviusly I might be missing a step

**Comment by dongido001** [comment]
@Paula-Alohas. are you using the latest CLI template (3.0)?

Then you need to move the proxy enpoints to the top. make sure it above "app.get(shopify.config.auth.path, shopify.auth.begin());".

**Comment by ionescurares** [comment]
@brdsmth 

Tried your middleware solution and it partially fixed the issue for me :(. I am getting **[shopify-app/ERROR] ensureInstalledOnShop did not receive a shop query argument | {shop: undefined}  **. Any thoughts on this would be appreciated
