### ISSUE TITLE
Initializing Rest client without using the session object throws a type error

### ISSUE THREAD

**Issue by requinchat42** [Shopify/shopify-api-js#637]
Initializing the Rest client without using the session object throws a type error:
```
new shopify.clients.Rest({
        domain: "session.shop",
        accessToken: "session.accessToken",
    });

```

throws: 'domain' does not exist in type 'RestClientParams'

**Comment by pomeo** [comment]
Try this
```
new shopify.Clients.Rest(session.shop, session.accessToken)
```

**Comment by eatoncw** [comment]
in v6 you'll need to pass in a session object with shop & accessToken keys.

You can see

```
public constructor(params: RestClientParams) {
    super({domain: params.session.shop});

    if (!this.restClass().CONFIG.isPrivateApp && !params.session.accessToken) {
      throw new ShopifyErrors.MissingRequiredArgument(
        'Missing access token when creating REST client',
      );
    }

    this.session = params.session;
  }
  ```
  
  So you'll need to change `domain` to `shop`

**Comment by mkevinosullivan** [comment]
The v6 `Rest` client takes a `session` object as the argument.
https://github.com/Shopify/shopify-api-js/blob/main/docs/migrating-to-v6.md#changes-to-api-clients

**Comment by willyou** [comment]
Wow, that's a huge change; what if we are using offline token as HTTP request?
