### ISSUE TITLE
Issue with the callback url from npm package v6

### ISSUE THREAD

**Issue by Cavmpt** [Shopify/shopify-api-js#638]
var express = require('express');
var router = express.Router();
require("@shopify/shopify-api/adapters/node") 
var shopifyStuff = require("@shopify/shopify-api")
const { shopifyApi, LATEST_API_VERSION } = shopifyStuff

/* GET home page. */
router.get('/', function(req, res, next) {
});

router.get('/auth/callback', async (req, res) => {
  // The library will automatically set the appropriate HTTP headers
  console.log('___hit___')
  const shopify = shopifyApi({
    // The next 4 values are typically read from environment variables for added security
    apiKey: "my key",
    apiSecretKey: "my key",
    scopes: scopes,
    hostName: "ff52-147-124-71-250.ngrok.io",
    apiVersion: LATEST_API_VERSION,
    isEmbeddedApp: false,
  });
  const callback = await shopify.auth.callback({
    rawRequest: req,
    rawResponse: res,
  });
  console.log('callback', callback)
})

router.get('/auth', async (req, res) => {
  
  const shopify = shopifyApi({
    // The next 4 values are typically read from environment variables for added security
    apiKey: "my key",
    apiSecretKey: "my key",
    scopes: scopes,
    hostName: "ff52-147-124-71-250.ngrok.io",
    apiVersion: LATEST_API_VERSION,
    isEmbeddedApp: false,
  });
  
  await shopify.auth.begin({
    shop: shopify.utils.sanitizeShop(req.query.shop, true),
    callbackPath: '/auth/callback',
    isOnline: false,
    rawRequest: req,
    rawResponse: res,
  });
});

module.exports = router;

const scopes = [
  "read_analytics",
  "write_assigned_fulfillment_orders",
];

Hello this is my code that i running with the help of ngrok in order to get access to the admin api with v6. 

It is returning me 

Oauth error invalid_request: The redirect_uri and application url must have matching hosts. I think something is wrong with the oauth2.0 encoding in the package itself please let me know thank you

**Comment by cquemin** [comment]
@Cavmpt it seems that you have not used the Shopify CLI to generate the skeleton of your app. Obvisouly it is not mandatory to do so, but you might want to have a look at [this turorial](https://shopify.dev/apps/getting-started/create) and generate a node app. It should give you an idea of how we configure the use for `shopifyApi`, the setup for the `callback` for the auth process. You'll also see how we handle the tunnelling. The CLI takes care of most of it for you but you can customize the skeleton generated for you to your liking.
