### ISSUE TITLE
ensure-billing.js: 29: session: callback.session

### ISSUE THREAD

**Issue by valorloff** [Shopify/shopify-api-js#640]
# Issue summary

after migrating to V6 in your migrate instruction indicated in ensure-billing.js:
```
confirmationUrl = await shopify.billing.request({
        session: callback.session,
        plan: Object.keys(shopify.config.billing)[0],
        isTest: !isProdOverride,
      });
```
 but in production i got "callback undefined" error

## Reduced test case

i change to 
```
confirmationUrl = await shopify.billing.request({
        session,
        plan: Object.keys(shopify.config.billing)[0],
        isTest: !isProdOverride,
      });
```

now error go away, but is it allowed here ?
what is purposes callback was for ?

**Comment by mkevinosullivan** [comment]
@valorloff That's a copy and paste error in the migration guide ... I think you're referring to this [section](https://github.com/Shopify/shopify-api-js/blob/main/docs/example-migration-v5-node-template-to-v6.md#11-update-the-billing-helper)?

As you can see in the call to `shopify.billing.check()` earlier in the method, it's just `session`, which is what it also should be in the call to `request`.

Thanks for pointing this out, will correct.
