### ISSUE TITLE
Authenticated requests without full session object from CRON

### ISSUE THREAD

**Issue by eatoncw** [Shopify/shopify-api-js#643]
## Overview/summary
In v5 authenticated requests (rest & graphql) could be made with just positional args of shop and access token. Now you need to pass in the whole session object.

This makes the method of making requests, from say a CRON, unclear. Guidance on initializing an authenticated client would be helpful - what is the workflow? 

Eg
```
import {Session} from '@shopify/shopify-api';
const session = new Session({
  id: 'session-id',
  shop: 'shop.myshopify.com',
  state: 'state1234',
  isOnline: true,
  accessToken: 'from db',
});
const clone = new Session({...session, id: 'newId'});
const client = new shopifyClient.clients.Graphql({session: clone})
```

Is this workable (given shop and accessToken are valid)?

But what are id, state, and isOnline and do they impact the Rest or Grapql clients?

Basically an example workflow or more detailed description of this would be appreciated.
...

## Motivation

> What inspired this enhancement?

I'd like to make authenticated requests from a CRON without knowledge of an active or expired/unexpired session. We are saving the accessToken to a db (which I understand does not expire).

The main fear is that implementing an authenticated client from a basically session-less service might fail is the session is not valid (and the only way to update the session is thru re-oauth). This is general concern of mine when dealing with OAuth in server-server communications, so again an example or explanation in the docs would be appreciated.
...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [ x] I have described this enhancement in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
@eatoncw 

> We are saving the accessToken to a db (which I understand does not expire).

I'm going to interpret this to mean that in your call to `auth.begin` you are requesting an `offline` access token (i.e., the `isOnline` param to `auth.begin` is `false`).

The session id in that case can be generated using `shopify.session.getOfflineId()` which takes a `shop` argument.
`state` is only useful during the initial OAuth flow and can be ignored, `isOnline` is `false`.

It's generally recommended to store the whole session returned from `shopify.auth.callback` for later lookup and use.

**Comment by ozzyonfire** [comment]
If your access token is `offline`, then it will never expire and you can use that session (or even just the access token) to access Shopify APIs

**Comment by mkevinosullivan** [comment]
@eatoncw What @ozzyonfire said!  `offline` tokens don't expire, making them ideal for background/batch processing/cronjob type activities.

**Comment by mkevinosullivan** [comment]
Since there's not been an update in a few weeks, I'm going to assume this worked.
