### ISSUE TITLE
Enable a way to pass information through the OAuth Process 

### ISSUE THREAD

**Issue by RobinKemna** [Shopify/shopify-api-js#651]
## Overview

Switching to the new v6 of this library we faced a problem with shopifys admin links.

We have to use several admin links for our application that e.g. link the merchant from his order list straight to our app including the selected order ids. If we run an app using the online sessions we have to reauthenticate once a day, cause the session expires which results in the first admin links used forwarding the merchant back to the root page of our app instead of opening the right page. To solve this, we will need to pass the referrer / initially requested url through the OAuth process to redirect the user after successfully passing the process back to this url. The new shopify.auth.callback / shopify.auth.begin functions do not support to pass any additional data and the state variable is used for the nonce as of security reasons (so far my understanding). Further adjusting the state variable or cookie content is not possible due to the fact, that this library takes care of the whole implementation.

Headers are also removed for a node.js / typescript based application - so no way to add the additional information here.

Thus we end up in the situation, that we either have to fallback to offline sessions or in the described scenario, where the user gets redirected to a static route in our app once successfully completed the flow - which is not ideal tbh.

Is there a way to get around this problem without switching to offline sessions that I have missed?

If not I would like to request it as a new feature.

**Comment by paulomarg** [comment]
I think this is actually a bug.

The ideal way of doing this would be to add a middleware before you call `shopify.auth.begin` to set the cookie, but as you mentioned, we're ignoring cookies (and any other headers) that are already set by that point. We should be adding our own cookies on top of what comes in, rather than overriding everything. I'll put up a PR to fix this.
