### ISSUE TITLE
Docs state to import "shopifyApi", but the import is not there...and how do you process webhooks, docs are incomplete

### ISSUE THREAD

**Issue by Zelfapp** [Shopify/shopify-api-js#678]
[Documentation](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/webhooks.md#note-regarding-use-of-body-parsers) is not getting me to the point of understanding how to process webhooks. My file is `shopifyWebhook.ts`, so typescript. Docs state to import `{ shopifyApi }`, but typescript errors, that import does not exist. So instead I use `Shopify` in the import.

![image](https://user-images.githubusercontent.com/11559805/212198109-828fed06-ab2d-445a-a4b1-b32598e16320.png)

Searching on SO `Shopify.Webhooks.Registry.process` appears to be the direction I should go, not `shopifyApi`, but again, how do I validate the webhook and what does `process` return? I'm assuming it returns a webhook JSON doc?

```node
import { onRequest } from 'firebase-functions/v2/https'
import { logger } from 'firebase-functions/v2'
import express from 'express'
import cors from 'cors'
import '@shopify/shopify-api/adapters/node'
import Shopify from '@shopify/shopify-api'
import { debug } from './lib/constants'

const app = express()

// Automatically allow cross-origin requests
app.use(cors({ origin: true }))
// Parse application/json
app.use(express.json())
// Support json encoded bodies and url encoded bodies
app.use(express.urlencoded({ extended: true }))

/**
 * Shopify order webhooks.
 */
app.post('/order', express.text({ type: '*/*' }), async (req, res) => {
  if (debug) {
    logger.info(req.params)
  }

  try {
    // TODO, how to validate incoming webhook?

    const shopify = Shopify.Webhooks.Registry.process(req, res)

    // TODO, what do we do with process response?
  } catch (error) {
    logger.info(error)
  }

  res.send({})
})

exports.endpoint = onRequest(
  {
    region: ['us-east4'],
  },
  app,
)
```

- `@shopify/shopify-api` version: ^5.3.0
- Node version: 18
- Operating system: Manjaro Linux

## Expected behavior

Need docs on how the webhook is validated and how we handle the response of `process` and what `process` returns.

**Comment by mkevinosullivan** [comment]
@Zelfapp The documentation you're referring to is for the latest version of the API library, v6, which is a complete revamp of the entire package compared to v5.  Would recommend that you use the latest version of the library package.
