### ISSUE TITLE
Supported Pagination with REST Resources

### ISSUE THREAD

**Issue by deldrid1** [Shopify/shopify-api-js#683]
## Overview

Can [REST pagination](https://shopify.dev/api/usage/pagination-rest) support be added to the REST API, specifically with mounted REST Resources?

Guessing these would be some new methods or a major version, but the `.all()` methods are fairly useless right now.  i.e., this will only return 50 articles instead of all of them.

```
shopify.api.rest.Article.all({
  session,
  blog_id: ...
})
```  

I'm personally a big fan of Async Generators for the API here. [Stripe uses these in their node.js package](https://github.com/stripe/stripe-node/blob/master/lib/autoPagination.js) along with several other handy methods if you like other accessors and want some inspiration.  

I implemented something like this using the Storefront API (that fully respects rate limiting, etc.), but the Shopify backend is returning crap pageInfo and inconsistent numbers of things (I'll be opening a support ticket for that) and was disappointed to see that the REST API didn't have this capability.

![image](https://user-images.githubusercontent.com/583660/213755039-b2bd7093-36b2-4201-9eaf-8d637b6b757f.png)

**Comment by paulomarg** [comment]
Hey @deldrid1, you're right - we have support for it in place but there's no documentation yet. I'll make sure this is covered in our docs. Thanks for raising it!
