### ISSUE TITLE
Set permanent access token for private app installed on only one store.

### ISSUE THREAD

**Issue by Zelfapp** [Shopify/shopify-api-js#700]
The [shopifyApi reference](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/shopifyApi.md) does not have a private app permanent access token property. I have a custom private app that is installed on only one store and I'm trying to understand how to establish a connection using a permanent access token.

- `@shopify/shopify-api` version: 6.1.0
- Node version: v16.16.0
- Operating system: Manjaro Linux

I'm looking at the [Session object](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/session-storage.md#basics) docs and I'm guesing that a private app connection is made using an **"offline" session**? Based on this assumption, I'm setting a `Session` with `SessionParams`. I'm confused by creating the `shopifyApi` object though to gain access to "offline" sessions, which seems geared to run through oAuth, with the `apiKey` and `apiSecretKey`, and then having to create a `Session` with the permanent access token `accessToken` and this is referred to being "offline". 

**Am I getting close with the code below???** I have yet to test it, but TS and lints are passing.

On the [performing oAuth doc](https://vanguardmil.myshopify.com/admin/settings/apps/development/26860650497/overview), it states "private apps are unable to perform OAuth, because they don't require an access token to interact with API.", but there is no link or documentation from this note, explaining what to do for private apps. And to create an "offline" session, which I think is the way you create a private app connection, it asks for an `accessToken`, which negates the performing oAuth doc note cited, if indeed "offline" sessions are how you create a private app connection.

Adding to the confusion, is why the `shopifyApi` object requires the `apiKey`, `apiSecretKey`, and `scopes` which are not required  for a private app, because private apps do not use oAuth and scopes have already been established when installing the private app in Shopify admin. The `isPrivateApp` flag in the `shopifyApi` object adds to the confusion, as well, because it gives you the impression that you can create a private app connection from the `shopifyApi` object. 

This is a great app, but you shouldn't have to dig around so much to understand and guess how it works for a private app.

```node
// Is this how you initialize a private app connection to gain access to "clients" functionality?
import '@shopify/shopify-api/adapters/node'
import { shopifyApi, LATEST_API_VERSION, Session } from '@shopify/shopify-api'
const debug = process.env.FUNCTIONS_EMULATOR === 'true'

const shopify = shopifyApi({
  apiKey: 'myprivateappkey',
  apiSecretKey: 'myprivateappsecret',
  apiVersion: LATEST_API_VERSION,
  isPrivateApp: true,
  scopes: ['read_products'],
  isEmbeddedApp: false,
  hostName: debug ? '127.0.0.1:5001' : 'shop.myshopify.com',
})

const sessionId = shopify.session.getOfflineId('shop.myshopify.com')
const session = new Session({
  id: sessionId,
  shop: 'shop.myshopify.com,
  state: 'state',
  isOnline: false,
  accessToken: 'permanentAccessToken',
})

const client = new shopify.clients.Rest({ session: session })
```

On older v5 version, the following code, just two lines, gave me access to all REST APIs, but I see this is now [deprecated](https://github.com/Shopify/shopify-api-js/blob/main/docs/migrating-to-v6.md#changes-to-api-clients). If this is just the way it is in v6, I guess creating the `shopifyApi` object, though confusing for a private app, is not a big deal to get access to the `shopify.session.getOfflineId` and `shopify.clients`. IMO, Just needs to be more clear somewhere in the docs what "offline" means, or a better yet a one page doc with the title "How to create a private app connection" that has the exact steps to establish a private app connection, and use the word "private" app rather than "offline".

```node
import Shopify from '@shopify/shopify-api'

const client = new Shopify.Clients.Rest(
  'mystore.myshopify.com',
  'permanentAccessTokenString',
)
```

## Expected behavior

It would be more intuitive if the `shopifyApi` init object gave the option to either enter a private access permanent token or the apiKey and apiSecret. And, if a private access permanent token is provided in the `shopifyApi` object, that the underlying functionality like REST would know that no session was needed. Like in v5, where it took just two lines of code. If this is not in the roadmap, it would be great to have a better example of how to use offline sessions with a private app, and have that documentation on just a single page in the docs for private apps. Covering how to load a Session with a permanent access token, in conjunction with creating the required `shopifyApi` object, and explain why the apiKey, apiSecret, and scopes are required even though you have a permanent access token. 

Finally, on the Shopify doc below, private apps do not use oAuth or sessions, so the definitions and concepts in shopify-api-js are a bit confusing for a private app, IMO.

### [Types of authentication and authorization methods](https://shopify.dev/apps/auth#types-of-authentication-and-authorization-methods)
![image](https://user-images.githubusercontent.com/11559805/215670628-ba542c6c-009c-4b05-b9b5-f004d7e3746a.png)

## Actual behavior

Not clear how to use a permanent access token for a custom private app.

## Steps to reproduce the problem

1. Create a custom private app.
1. Try to initialize the shopify REST client using a permanent access token.

**Comment by ehvattum** [comment]
Registering an access token upon client creation is indeed a desired feature.

**Comment by mkevinosullivan** [comment]
When creating the client in a private app, a dummy session can be created like so

```js
const session = new Session({
  id: 'not-a-real-session-id',
  shop: 'shop.myshopify.com,
  state: 'state',
  isOnline: false,
});
const client = new shopify.clients.Rest({ session: session })
```

When `config.isPrivateApp` is set to `true`
- only the `shop` property is used by the client - the other three (`id`, `state`, `isOnline`) properties are ignored (but are required when creating a `Session` object).
- `config.apiSecretKey` is used as the access token, and is read directly from the config (no need to set the `accessToken` property of the dummy session as it will be ignored).

Essentially, `config.apiSecretKey` is the _permanent access token_ for a private app.

Will add some documentation regarding this to the library - thanks for highlighting the lack thereof.

**Comment by Zelfapp** [comment]
Thank you @mkevinosullivan for the quick reply. So the following is correct then for a private app based on what you're stating. Curious, are the `apiKey` or `scopes` evaluated when `isPrivateApp` then? E.g. what if I accidentally left out a scope or made the `scopes` and empty array?

```node
const shopify = shopifyApi({
  apiKey: 'myprivateappkey',
  apiSecretKey: 'myPermanentAccessToken',
  apiVersion: LATEST_API_VERSION,
  isPrivateApp: true,
  scopes: ['read_products'],
  isEmbeddedApp: false,
  hostName: debug ? '127.0.0.1:5001' : 'shop.myshopify.com',
})

const session = new Session({
  id: 'not-a-real-session-id',
  shop: 'shop.myshopify.com,
  state: 'state',
  isOnline: false,
});

const client = new shopify.clients.Rest({ session: session })
```

**Comment by mkevinosullivan** [comment]
@Zelfapp The `scopes` can be omitted, as it defaults to an empty scopes array internally anyway and (from a quick search through the library code) is only used when doing OAuth, validating sessions, etc., which won't apply to private apps.

As for the `apiKey`, while it's mostly used as part of the OAuth process, it is also used in a few other places (e.g., `shopify.auth.getEmbeddedAppUrl()`), so I'd recommend setting the `apiKey` to be that of your private app.

**Comment by cjauvin** [comment]
As a total newcomer to this project, I must say that I struggled quite a bit to understand why the flow of making offline calls to a private app (with simply an access token) didn't seem possible, according to the documentation. Thankfully I stumbled upon that helpful thread, but I think this information should be made more clear in the docs, if possible. Thanks!

**Comment by Zelfapp** [comment]
@cjauvin the docs have been updated: https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/custom-store-app.md

**Comment by cjauvin** [comment]
@ianwatts22 I think the example contained in https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/custom-store-app.md is possibly not up to date, as it is different from what is in this thread above.

**Comment by ianwatts22** [comment]
Yeah the example above using `isPrivateApp` and `getOfflineID` worked, agree example in the docs/guide probably not up to date.

**Comment by mkevinosullivan** [comment]
@ianwatts22 `isCustomStoreApp` is the new config parameter, introduced in `v6.2.0` ([Feb 15](https://github.com/Shopify/shopify-api-js/blob/main/CHANGELOG.md#620---2023-02-15)); `isPrivateApp` also works but will be deprecated in `v7.0.0`.

**Comment by mywristbands** [comment]
@mkevinosullivan Thanks for providing the documentation on how to build a store-specific app. I've gone through the whole thing, but when I get to the part where I query for the product count, I get the error:
```
2023-03-16 20:59:46 | backend    | /Users/elias/Desktop/zenvy-app/web/node_modules/@shopify/shopify-api/lib/clients/rest/rest_client.js:15
2023-03-16 20:59:46 | backend    |     throw new ShopifyErrors.MissingRequiredArgument('Missing access token when creating REST client');
```

Here's how I've configured my shopifyApp:
```
const shopify = shopifyApp({
  api: {
    apiVersion: LATEST_API_VERSION,
    restResources,
    billing: undefined,
  },
  auth: {
    path: "/api/auth",
    callbackPath: "/api/auth/callback",
  },
  webhooks: {
    path: "/api/webhooks",
  },
  sessionStorage: new SQLiteSessionStorage(DB_PATH),
  apiKey: process.env.APP_API_KEY,
  apiVersion: LATEST_API_VERSION,
  apiSecretKey: process.env.ADMIN_API_ACCESS_TOKEN,
  isCustomStoreApp: true,
  scopes: [
    'write_customers',
    'write_products'
  ],
  isEmbeddedApp: false,
  hostName: process.env.HOST_NAME,
  restResources,
});
```
Basically I added the new fields from [custom-store-app tutorial](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/custom-store-app.md) to the default configurations generated from the [npm init @shopify/app@latest app](https://shopify.dev/docs/apps/getting-started/create#step-1-create-a-new-app). As you can see, I have set the `apiSecretKey` to my Admin API access token (NOT the API secret key), so I'm not sure why it's not working.  Also note that I've tried logging all the `process.env` fields, and they are all correctly configured.

Also just FYI, I noticed that the tutorial is partially out-of-date. The line:
`const session = shopify.session.customAppSession("my-shop.myshopify.com");`
should be:
`const session = shopify.api.session.customAppSession("my-shop.myshopify.com");`

And same for the `shopify.rest` commands, where it should be `shopify.api.rest`

**Comment by mywristbands** [comment]
I was able to figure it out! It turns out you need to move some of the configuration parameters into the `api` object. Here's how I've now configured my shopifyApp:
```
const shopify = shopifyApp({
  api: {
    apiVersion: LATEST_API_VERSION,
    restResources,
    billing: undefined,
    isCustomStoreApp: true,
    apiKey: process.env.APP_API_KEY,
    apiSecretKey: process.env.ADMIN_API_ACCESS_TOKEN,
  },
  auth: {
    path: "/api/auth",
    callbackPath: "/api/auth/callback",
  },
  webhooks: {
    path: "/api/webhooks",
  },
  sessionStorage: new SQLiteSessionStorage(DB_PATH),
  scopes: [
    'write_customers',
    'write_products'
  ],
  isEmbeddedApp: false,
  hostName: process.env.HOST_NAME,
});
```

@mkevinosullivan It would be great if someone could update the documentation to reflect this new required format.
