### ISSUE TITLE
Create a Client for apps made in the shopify admin

### ISSUE THREAD

**Issue by dbzx10299** [Shopify/shopify-api-js#707]
## Overview
In order to get a session id, the user needs to go through the oauth flow, however, if we create an app in the shopify admin, there is no need to go through the oauth flow since we already have our access tokens. I have tried for many hours now to get this to work and I don't know if I am missing something small, but I can't seem to skip the oauth flow for apps that are made in the admin and therefore not embedded.

If I am mistaken , please add a small text to the docs here addressing this. The `shopify.clients.Rest()` function takes a sessionId and which requires going throught the oauth flow, which we don't need to do if the app is created in the admin

**Comment by danieljarrett74** [comment]
I second (or third) this.  @zchen3000 's solution looks like it might work but it also looks like a hack.  At the very least it would be nice to have some documentation around this.

**Comment by jonmast** [comment]
Looks like this is sort of fixed now, there's a `shopify.session.customAppSession` helper to generate the dummy session for you.

Guide: https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/custom-store-app.md

**Comment by danieljarrett74** [comment]
Correct me if I'm wrong but i don't believe the custom app session is something different than what is being requested @mkevinosullivan

**Comment by YaminNather** [comment]
@dbzx10299 But we lose type support, the whole point of the API.
