### ISSUE TITLE
Need to get plain JSON from mounted REST resources rather than custom prototypes

### ISSUE THREAD

**Issue by Zelfapp** [Shopify/shopify-api-js#711]
Is there a `.toJSON()` function on mounted resources, to get plain JSON back or do we simply use js to convert the custom prototypes returned from mounted resources by doing something like `JSON.parse(JSON.stringify(transactions))`? I'm not seeing functionality to get plain JSON in [mounted resources doc.](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/rest-resources.md#using-rest-resources)

Shopify shows [examples of mounted resources for nodejs](https://shopify.dev/api/admin-rest/2022-10/resources/transaction#get-orders-order-id-transactions) and return types examples are plain JSON, but custom prototypes are returned. My hope is that my devs will be able to refer to nodejs examples on Shopify API Rest examples, which are showing mounted resources being used and be able to rely on the Shopify example responses to craft functionality in our app.

![image](https://user-images.githubusercontent.com/11559805/216524416-f07bfc16-3ea1-46c4-8e60-958947907b19.png)

The issue is that custom prototypes returned from mounted resources (for my use case), cannot be saved in Cloud Firestore. E.g. this mounted resource call to get all transactions returns a custom prototype "Transaction"...

```js
const transactions = await shopify.rest.Transaction.all({
  session,
  order_id: 123456789,
})
```

... which generates the following firestore error:

```
Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "Transaction" (found in field "transaction_data.`0`"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
```

- `@shopify/shopify-api` version: 6.1.0
- Node version: v16.16.0
- Operating system: Manjaro Linux

## Expected behavior

Have the option to get plain JSON back as the [examples responses on Shopify describe](https://shopify.dev/api/admin-rest/2022-10/resources/transaction#get-orders-order-id-transactions) from mounted resources.

## Actual behavior

Custom prototypes are returned rather than plain JSON.

## Steps to reproduce the problem

1. Use the Transaction mounted resource to get all transactions on an order and try to store in Cloud Firestore.

**Comment by mkevinosullivan** [comment]
👋🏻 @Zelfapp Sorry for the delay in responding (I thought I had already, my mistake).

As part of a fix for another issue, we added a `toJSON()` to the base class of the mounted resources in PR #690, and this was released as part of `6.2.0` on February 15 ... have you tried it with the latest release of the library?
