### ISSUE TITLE
Support admin.shopify.com as base host

### ISSUE THREAD

**Issue by kelreel** [Shopify/shopify-api-js#715]
In many places (billing, authorization), URL generation using the store's domain. 
This creates unnecessary redirect, incorrect redirect URLs after the billing charge and potentially creates various problems.

**Comment by rycastaneda** [comment]
Encountering this too 
![image](https://user-images.githubusercontent.com/4694510/217507380-ffd2bade-a1b9-4516-90b0-568554a99006.png)
clicking the warning redirects to url with force_legacy parameter to a host name with the myshopify.com host.

**Comment by mkevinosullivan** [comment]
@kelreel @rycastaneda Is this still happening?  I'm unable to reproduce this, though I did see it a few times a while ago.  I think this may have been a temporary issue as the Unified Admin was rolled out incrementally across all stores.

Please confirm if it's still occurring

**Comment by kelreel** [comment]
@mkevinosullivan It would be useful if the return urls in the billing had a base host admin.shopify.com (cancel charge does not work after the redirect). Otherwise, I didn't notice any problems.
