### ISSUE TITLE
HELP Adding shop information on first installation

### ISSUE THREAD

**Issue by tamir-boaideas** [Shopify/shopify-api-js#718]
Using shopify/cli 3.36.1 and shopify-api 6.1.0, I am trying to add my own logic to the installation process.

I read the [auth docs](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/auth/README.md) but could use some help.

I want additional fields in the shopify_sessions table and I understand the code should go here

```
app.get(
	shopify.config.auth.callbackPath,
	shopify.auth.callback(),
	shopify.redirectToShopifyOrAppRoot()
);
```

I didn't understand how to get in the middle and add attributes to the session object before it passes to the storeSession method. 

As a first step, I changed the code following [this readme](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/auth/callback.md) like this:

```
app.get(
	shopify.config.auth.callbackPath,
	async (req, res, next) => {
		const callback = await shopify.auth.callback({
			rawRequest: req,
			rawResponse: res,
		});
		console.log(callback);
		console.log(callback.session);
		next();
	},
	shopify.redirectToShopifyOrAppRoot()
);
```
But the first console.log showed [AsyncFunction (anonymous)] and the second one showed undefined. The code crashed after both logs with an error that says res.locals.shopify is undefined (even though I haven't done anything yet).

Additionally, I couldn't figure out where and when the call to storeSession occurs.

I would greatly appreciate your assistance

**Comment by athahersirnaik** [comment]
Create a middleware just after shopify.auth.callback().

**Comment by tamir-boaideas** [comment]
> Create a middleware just after shopify.auth.callback().

Thank you for your reply. 
How will I gain access to the session object in the next middleware? And if I modify it then, will it be passed to storeSession with my modifications or is it already stored?

**Comment by vladbannik** [comment]
I think you need use `res.locals.shopify` in next middleware

**Comment by tamir-boaideas** [comment]
The res.locals.shopify.session works, Thank you all!

**Comment by ludovicraymond** [comment]
Do you have a solution to do the same thing after the first auth has been validated ?
If I use the middleware for /* the res.local.shopify is undefined.
I would like to be sure if the user click on cancel button during the paiement on app installation I can recheck his subscription.
Do you have a solution for that?
