### ISSUE TITLE
TypeError: shopify.session.customAppSession is not a function

### ISSUE THREAD

**Issue by Robin2009** [Shopify/shopify-api-js#721]
# Issue summary

- `@shopify/shopify-api` version: ^6.1.0
- Node version: v18.14.0
- Operating system: Win11

```
const session = shopify.session.customAppSession(shopifyStoreHost);
TypeError: shopify.session.customAppSession is not a function
```

## Expected behavior

As the store owner I'm trying to build an app for my own. Base on the guid [Creating a store-specific custom app](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/custom-store-app.md), I should call method `shopify.session.customAppSession` to create a session object before requests. Yet got error says 
`TypeError: shopify.session.customAppSession is not a function`.

Sorry, new to Shopify & Shopify-api. Need help to cross this issue. Thanks so much!

**Comment by hinsxd** [comment]
this feature was merged last week and is not released yet

https://github.com/Shopify/shopify-api-js/pull/710
