### ISSUE TITLE
REST resources are not accessible as described in documentation

### ISSUE THREAD

**Issue by tamir-boaideas** [Shopify/shopify-api-js#738]
# Issue summary
As stated in the documentation multiple times, you should import the shopify app instance from shopify.js, and then reach to shopify.rest.Order (or any other resource) in order to call the admin order API.
However, I receive an error stating that this is an undefined variable.

Eventually, I figured out a small change that makes it work for me: shopify.**api**.rest.Order, but the documentation doesn't mention this.
This occurs with a blank app node template without any changes on my part.

Is this the correct way to get the REST resources and the documentation is incorrect or am I doing something wrong?

- `@shopify/shopify-api` version: 6.2.0
- Node version: 18.11.0
- Operating system: MacOS

## Expected behavior

shopify.rest.Order should return the REST resouce (order is just an exmaple, it happens with every REST resource).

## Actual behavior

Shopify.rest.Order is undefined, but shopify.rest.api.Order returns the REST resource.

## Steps to reproduce the problem

1. Create a new shopify/cli node app template
2. Import shopify from shopify.js 
3. Try to make an API call to a REST resource (order for example) using shopify.rest.Order.find
4. Try to make an API call to a REST resource (order for example) using shopify.api.rest.Order.find

**Comment by mkevinosullivan** [comment]
@tamir-boaideas The Node app template generated with shopify/cli uses the `@shopify/shopify-app-express` package.

In that template, `shopify` is the return value of [`shopifyApp`](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-express/docs/reference/shopifyApp.md#return) (from the `@shopify/shopify-app-express` package), NOT `shopifyApi` (from the  `@shopify/shopify-api` package).

The return value of `shopifyApp` includes an `api` property, which is the return value from `shopifyApi` as used by the `shopifyApp` call.  Hence, _for the template_, `shopify.api.rest.Order` is the correct usage.

All the documentation in this current repo is for `@shopify/shopify-api`, where `shopify` refers to the return value of [`shopifyApi`](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/shopifyApi.md#return).
