### ISSUE TITLE
I tried to fetch all orders between date range using Shopify REST API, but the result data is wrong.

### ISSUE THREAD

**Issue by quanseng** [Shopify/shopify-api-js#758]
"nodejs": 16.16.0
"@shopify/shopify-api": "6.2.0"
when I get all orders between dates, it gets wrong result.

      const created_at_min = "2023-03-07 00:00:00.000"
      const created_at_max = "2023-03-07 23:59:59.000"

      const orders = await shopify.rest.Order.all({
        session: session,
        status: "any",
        created_at_min: created_at_min,
        created_at_max: created_at_max
      });
      console.log(orders.length) /// 25 : this is wrong
      
But, when I get total order count, it gets correct result:

      const created_at_min = "2023-03-07 00:00:00.000"
      const created_at_max = "2023-03-07 23:59:59.000"

      const ordersCount = await shopify.rest.Order.count({
        session: session,
        status: "any",
        created_at_min: created_at_min,
        created_at_max: created_at_max,
      });
      console.log(ordersCount) /// count: 58 : this is correct     

Why are  these 2 results different?

**Comment by quanseng** [comment]
> Paging?

No, 
Actually, default page size is 50. and this is not due to the paging.

**Comment by nicemaker** [comment]
Maybe you need proper ISO String?
```
2023-03-07T00:00:00.000Z
```
