### ISSUE TITLE
webhook.process validation fails in custom apps

### ISSUE THREAD

**Issue by SuperKXT** [Shopify/shopify-api-js#772]
# Issue summary

The HMAC sent in the HTTP webhook header validates against the passed `apiSecretKey`. In a custom app, the documentation indicates using the shared secret instead.
This is the relevant line.

https://github.com/Shopify/shopify-api-js/blob/2e01ac6a383db6f3c9c574571f6b175eaa0ef517/lib/webhooks/process.ts#L53

- `@shopify/shopify-api` version: 6.2.0
- Node version: 19.7.0
- Operating system: Pop!_OS 22.04 LTS x86_64

## Expected behavior
`webhook.process` should validate the HMAC correctly

## Actual behavior
webhook validation fails. 
I'm side-stepping the issue by manually setting `apiSecretKey` to the `sharedSecret` just before validation. This works but feels like an unnecessary hack.

```ts
SHOPIFY.config.apiSecretKey = CONFIG.shopify.sharedSecret;
await SHOPIFY.webhooks
	.process({
		rawBody: request.body,
		rawRequest: request,
		rawResponse: response,
	})
	.catch((error) => {
		LOGGER.error(`Error in webhook handler: ${getErrorMessage(error)}`);
	})
	.finally(() => {
		SHOPIFY.config.apiSecretKey = CONFIG.shopify.accessToken;
	});
```

**Comment by mkevinosullivan** [comment]
For a store-specific custom app (which I think you're referring to here), the `apiSecretKey` should be set to the API Admin Access Token ... is this what you're referring to as the shared secret?

https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/custom-store-app.md
