### ISSUE TITLE
Using webhooks in dev stores throws 404 when offline

### ISSUE THREAD

**Issue by tamir-boaideas** [Shopify/shopify-api-js#775]
# Issue summary

During app development, a tunnel connects the app to your local environment.

Webhooks are registered through the tunnel and everything works as expected.

When you don't work on the app, the webhook still points to the same URL, so if something triggers the webhook (e.g., you have an order/created webhook and you created an order to test something else that has no relevance to the app), the webhook will fail with 404.

- `@shopify/shopify-api` version: 6.2.0
- Node version: 18.11.0
- Operating system: MacOS

![image](https://user-images.githubusercontent.com/87411227/225639423-e547a96f-9fcb-4922-9062-1480571796ca.png)

## Expected behavior

When the development server isn't running, webhooks should be disabled (or ignored).

## Actual behavior

Webhooks keep firing and failing with a 404 status code

## Steps to reproduce the problem

1. Start a development app with the CLI and install it on a dev store
2. Register a webhook via the app (orders/create for example)
3. Create an order and see that the webhooks work
4. Kill the dev server
5. Create another order and watch the webhook fail with 404 and retry (over and over)

**Comment by mkevinosullivan** [comment]
If an app has registered a webhook with the Shopify system, and the app is still installed on the store, Shopify will always attempt to deliver events for that webhook... this is by design for production apps to work properly.
