### ISSUE TITLE
shopify.auth.begin redirected you too many times when app is embedded

### ISSUE THREAD

**Issue by mariusa** [Shopify/shopify-api-js#780]
# Issue summary

Using shopify.auth.begin() works fine for a non-embedded app.

With an embedded app and using fastify. App was installed (that worked fine). 
Loading the app again gives error `redirected you too many times`

```
fastify.get('/api/auth', async (req, reply) => {
  return await shopify.auth.begin({
             shop: shopify.utils.sanitizeShop(req.query.shop, true),
             callbackPath: '/api/auth-return',
          isOnline: false, 
             rawRequest: req.raw,
             rawResponse: reply.raw,
        })
})
```

Console network shows 
1. loading 
https://eudev3.myshopify.com/admin/oauth/authorize?client_id=38887f4dc5adbd90d9ca4a86ba749704...&scope=changed...&redirect_uri=...
once (302)

2. many redirects to `https://mydev.myshopify.com/admin/oauth/request_grant?access_change_uuid=58428e9..&client_id=3888..`

The cause is app being loaded in an iframe, and `shopify.auth.begin` should be called top-level

How can we do that, since we can't control Shopify loading app's `/api/auth` ?
Should `shopify.auth.begin` handle both frame & top-level redirects?

![Screenshot from 2023-03-20 11-15-00](https://user-images.githubusercontent.com/1283842/226300466-8985451e-02a3-44cf-8d77-86b00f5b4301.png)

- `@shopify/shopify-api` version: 6.2
- Node version: 18
- Operating system: Linux

```
// logs
[shopify-api/INFO] Beginning OAuth | {shop: mydev.myshopify.com, isOnline: false, callbackPath: mypath}
is shown once

"OAuth started, redirecting to" is NEVER shown, but I see it in code at 
https://github.com/Shopify/shopify-api-js/blob/feba483853e8ab9a623853aac4606500d032ab54/lib/auth/oauth/oauth.ts#L94


shopifyApi() has `isEmbeddedApp: true`

```

**Comment by mkevinosullivan** [comment]
@mariusa To familiarize myself with working with Fastify, I created a (non-supported) [`app_template_fastify`](https://github.com/Shopify/shopify-app-template-node/tree/app_template_fastify) branch that should be a Fastify version of the default Node template app.  I can't say I did extensive testing but it did seem to install, uninstall, re-install, and populate products as expected.

**Comment by mariusa** [comment]
Thank you, that will help! I'll look into it and will also test oauth scope changing, then get back here.

**Comment by mariusa** [comment]
The fastify template helped! Thanks
