### ISSUE TITLE
Adding a RemixRun Adapter

### ISSUE THREAD

**Issue by fvaldes33** [Shopify/shopify-api-js#795]
## Overview

Would be nice to have a remix adapter for the shopify-api. It _technically_ can be done using remix's express server runtime but then you would have a the same issues as using the `shopify-app-template-node`. 

Would be nice to have all the code live in the remix convention versus maintaining a server block and then also your remix app.

**Comment by johannbuscail** [comment]
Any news or update? Have you found a way to make this work ?
