### ISSUE TITLE
Support multiple handlers for the same webhook topic

### ISSUE THREAD

**Issue by mhkafadar** [Shopify/shopify-api-js#827]
## Overview

I would like to propose some improvements to the webhook registration logic of the library. These changes aim to address the following issues:

1. **Deletion of unrelated topics during individual webhook registration:** Currently, when registering a new topic individually, the library removes existing topics with different names. For example, if a `COLLECTIONS_UPDATE` topic exists and you register an `APP_SUBSCRIPTIONS_UPDATE` topic in a separate registration call, the `COLLECTIONS_UPDATE` webhook will be deleted. This behavior is not desired, as developers may want to subscribe to multiple topics individually. It is worth noting that subscribing to multiple topics at once does not cause this issue.

2. **Limitation on registering the same topic with different URLs:** The library currently does not allow registering the same topic with different URLs. For instance, if you register an `APP_SUBSCRIPTIONS_UPDATE` topic with `domain.com/webhook`, trying to register the same topic with `domain.com/webhook-new` will result in the deletion of the previous one. This limitation has already been discussed in [issue #427](https://github.com/Shopify/shopify-api-js/issues/427), but no changes have been made. According to a response from SBD_ on [this Shopify community post](https://community.shopify.com/c/shopify-apis-and-sdks/multiple-subscription-to-webhook-using-same-app/m-p/806772#M52780), Shopify's API allows multiple subscriptions to the same webhook topic with different URLs.

To address these issues, I have implemented the necessary logic and introduced a new parameter `allowMultipleHandlers`, which is `false` by default to maintain the library's current behavior. To enable multiple handlers, you can use the following code:

```javascript
api.webhooks.register({
  session,
  allowMultipleHandlers: true,
});
```

I am happy to add tests and submit a PR if these changes align with the goals of the core contributors. You can review my code changes in my repository [here](https://github.com/mhkafadar/shopify-api-js/commit/2be7e42db49c501f1cc460bed054d9d0293141a5). Your feedback is much appreciated. Thank you.

**Comment by mhkafadar** [comment]
Hello @DavidWittness, and thank you for your response and efforts in reproducing the issue. I'd like to provide more details to help clarify the situation.

I am running the app on two different servers, both using the same API key and secret.

Issue 1:
On Server 1:

```js
// Subscribe to topics and bind handlers
const webhookPath = '/webhook-url-1';
const webhooks = [
  [
    WebhookTopic.PRODUCTS_UPDATE,
    this.webhooksService.handleProductUpdate.bind(this.webhooksService),
  ],
];

for (const [topic, handler] of webhooks) {
  await this.shopifyInitService.shopify.api.webhooks.addHandlers({
    [topic]: [
      {
        deliveryMethod: DeliveryMethod.Http,
        callbackUrl: webhookPath,
        callback: handler,
      },
    ],
  });
}

// Register webhooks for a store
await this.shopifyInitService.shopify.api.webhooks.register({ session });
```

After completing these steps, let's move on to Server 2:

```js
// Subscribe to topics and bind handlers (using a different url for the 2nd server)
const webhookPath = '/webhook-url-2';
const webhooks = [
  [
    WebhookTopic.UNINSTALL,
    this.webhooksService.uninstall.bind(this.webhooksService),
  ],
];

for (const [topic, handler] of webhooks) {
  await this.shopifyInitService.shopify.api.webhooks.addHandlers({
    [topic]: [
      {
        deliveryMethod: DeliveryMethod.Http,
        callbackUrl: webhookPath,
        callback: handler,
      },
    ],
  });
}

// Register webhooks for a store
await this.shopifyInitService.shopify.api.webhooks.register({ session });

```

Now, if you query the active webhooks for the store, you will only see the UNINSTALL webhook, and the PRODUCTS_UPDATE webhook will have been removed automatically.

Issue 2:
Follow the same steps as in Issue 1, but on the second server, add the PRODUCTS_UPDATE subscription instead of the UNINSTALL subscription. You will notice that the subscription from the first server has been removed, and only the PRODUCTS_UPDATE webhook with '/webhook-path-2' remains active.

**Comment by DavidWittness** [comment]
Thanks for adding some context to the issue. I would think running on two different servers wouldn't matter. 

Inside the `webhooks.register()` call, we [get the existing handlers](https://github.com/Shopify/shopify-api-js/blob/main/lib/webhooks/register.ts#L67) based on the config and current session. From that list of topics, we'll add new ones and [delete any leftovers](https://github.com/Shopify/shopify-api-js/blob/main/lib/webhooks/register.ts#L95). It's possible there is something in the stack causing these handlers to fall out of sync with each other.

@paulomarg, I'm not sure what the current intended functionality is right now. The platform supports multiple handlers per topic, but [this test](https://github.com/Shopify/shopify-api-js/blob/main/lib/webhooks/__tests__/register.test.ts#L188) would suggest that we'd only want one handler. Any thoughts on a path forward with this issue?

**Comment by DavidWittness** [comment]
I think option 2 is covered in @mhkafadar's proposed solution. 

Can you setup a PR with your proposed changes? I'll put it down and run a few tests, then update the docs.

**Comment by mhkafadar** [comment]
@DavidWittness Hi! Thank you!
I think I have to write tests before creating the PR, I need some time to write tests then I will open PR.

**Comment by mhkafadar** [comment]
Hello @DavidWittness any updates on your side? Thanks.

**Comment by mhkafadar** [comment]
Hello, it's been a while. Do you have any updates to share from your end?
