### ISSUE TITLE
No request body received in APP_UNINSTALLED webhook

### ISSUE THREAD

**Issue by huanhunx** [Shopify/shopify-api-js#829]
# Issue summary

I used these codes to register a webhook:
```js
const shopify = shopifyApi({
    // ... my configs
});

shopify.webhooks.addHandlers({
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks/uninstalled',
      callback: async (topic, shop) => {
         // something to do
      },
    },
});

// after oauth success
router.get('/auth/callback', async ctx => {
    const callback = await shopify.auth.callback({
      rawRequest: ctx.req,
      rawResponse: ctx.res,
    });

    shopify.webhooks.register({
        session: callback.session,
    }),

    // something to do
});
```

It works good here. But I got error when I receive the uninstall webhook

```js
router.post('/webhooks/uninstalled', async ctx => {
    console.log('--- uninstalled webhook');
    console.log(ctx.request.query); // No parameters received, it is an empty object
    console.log(ctx.request.body); // No parameters received, it is undefined
    console.log(ctx.req.body); // No parameters received, it is undefined

    try {
      await shopify.webhooks.process({
        rawBody: ctx.req.body,
        rawRequest: ctx.req,
        rawResponse: ctx.res,
      });
      console.log('Webhook processed, returned status code 200');
    } catch (error) {
      console.log(`Failed to process webhook: ${error}`); // Here throws an Error:  Cannot read property 'length' of undefined
    }
    ctx.body = 'ok';
});
```

I guess this error is because the `ctx.req.body` is undefined, but there's no params I received in this request.

- `@shopify/shopify-api` version: 6.2.0
- Node version: 14.17.1
- Operating system: MacOS

## Expected behavior

`shopify.webhooks.process` should work. My webhook handler's callback function should be triggered.

## Actual behavior

Throws an error `Cannot read property 'length' of undefined` when I call `shopify.webhooks.process` function.

## Steps to reproduce the problem

Like my sample code above.

**Comment by paulomarg** [comment]
Hi, thanks for your question. Starting with v6 of the library, the `rawBody` parameter expects a string containing the body, so your app will need to parse it (typically by using a body parser).

Please find some more details in [our documentation](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/webhooks.md#note-regarding-use-of-body-parsers). The docs mention express, but if you're using koa you could use `koa-body` or `koa-bodyparser` (just off the top of my head, there might be other options out there!).
