### ISSUE TITLE
Cannot read property 'Order' of undefined from shopify-express sdk

### ISSUE THREAD

**Issue by schapicool** [Shopify/shopify-api-js#831]
# Issue summary

- `@shopify/shopify-api` version:
- Node version: 6.2.0
- Operating system: macos

```
// Paste any relevant logs here
```

## Expected behavior

I can use shopify.rest.Order.all to request order list

## Actual behavior

it return UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Order' of undefined from shopify-express sdk

**Comment by mkevinosullivan** [comment]
@schapicool Please share how you are configuring the API ... this seems to indicate that the `shopify` object isn't being configured with the REST resource objects.
