### ISSUE TITLE
'adminApiAccessToken' does not exist in type 'ConfigParams'. Enable to start an instance for customApp.

### ISSUE THREAD

**Issue by yanisforcedtocode** [Shopify/shopify-api-js#845]
- @shopify/shopify-api": "^7.0.0"

When creating an instance of  shopifyApi for a customApp (previously privateApp) following this guide:
https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/custom-store-app.md
, adminApiAccessToken is not an acceptable property.

"Object literal may only specify known properties, and 'adminApiAccessToken' does not exist in type 'ConfigParams<RestResources>'.ts(2345)"

**Comment by dturton** [comment]
Hi @yanisforcedtocode this config worked for me. 

const shopify = shopifyApi({
	apiKey: "apikey",
	isCustomStoreApp: true,
	apiSecretKey: "accssstoken", // ---> I note that in a custom app I had to set the access token to the api secret key
	privateAppStorefrontAccessToken: "accssstoken",
	scopes: ["read_products"],
	hostName: "store.myshopify.com",
	apiVersion: ApiVersion.April23,
	isEmbeddedApp: false,
	logger: {
		level: LogSeverity.Debug,
		timestamps: true,
		httpRequests: true,
		log: async (severity, message) => {
			console.log(`[${severity}] ${message}`);
		},
	},
});

**Comment by kgrosvenor** [comment]
So apiKey should be "apiKey"? @dturton

**Comment by mkevinosullivan** [comment]
@yanisforcedtocode For API 7.0.0, to configure a custom store app, use this document from the 7.0.0 tag: https://github.com/Shopify/shopify-api-js/blob/v7.0.0/docs/guides/custom-store-app.md

What's currently on `main` (including the new `adminApiAccessToken` configuration property) is yet to be released (targeting May 8-10, 2023 for release)

**Comment by MayorBiney** [comment]
> @yanisforcedtocode For API 7.0.0, to configure a custom store app, use this document from the 7.0.0 tag: https://github.com/Shopify/shopify-api-js/blob/v7.0.0/docs/guides/custom-store-app.md
> 
> What's currently on `main` (including the new `adminApiAccessToken` configuration property) is yet to be released (targeting May 8-10, 2023 for release)

Can we please get an update when this is added.
