### ISSUE TITLE
I cant update assets with 2023-04 version REST Admin Assets API PUT Request

### ISSUE THREAD

**Issue by ekimcoskun** [Shopify/shopify-api-js#860]
# Issue summary
I cant update assets with 2023-04 version REST Admin Assets API PUT Request. The API can find assets with theme ID and key, but cant update.

- `@shopify/shopify-api` version: 2023-04
- Node version: v18.14.2
- Operating system: Windows

```
The query return this response logs:
Error: Received an error response (404 Not Found) from Shopify:
"Not Found"
 If you report this error, please include this id: 7bfa3dfe-cda0-46cf-a522-ee4a1410b549
```

Please fix this problem :)

**Comment by mkevinosullivan** [comment]
@ekimcoskun Please see the note regarding PUT and DEL requests of Asset in the 2023-04 Admin API on this page: https://shopify.dev/docs/apps/online-store/other-integration-methods/asset ... you are likely being impacted by this change.

**Comment by ekimcoskun** [comment]
Thank you so much for prompt reply. I found what I missed because of you.

**Comment by Furquan712** [comment]
@ekimcoskun  can you please how you solved it, I am also getting the sane issue ?

here is my code

app.get("/api/single_a", verifyRequest, async (req, res) => {
  try {
    const sessionId = await shopify.session.getCurrentId({
      rawRequest: req,
      rawResponse: res,
    });
    const session = await sessionHandler.loadSession(sessionId);
    
    const client = new shopify.clients.Rest({session});
 
    const response = await client.get({
      path: 'themes/id/assets',
      query:{
        asset:{
          key: "assets/animations.js"
        }
      }
    });
    
    console.log("value", response.body.asset.value )
    response.body.asset.value = "<p>Heloo world </p>"
    console.log("value changed", response.body.asset.value )
    
    await response.save({
      update: true,
    });
     
    // await client.put({
    //   path: `themes/id/assets`,
    //   data: response.body.asset
      
    // });
     
    console.log("Layout of theme liquid", response);
    
    res.status(200).json({ response }); // Assuming you want to send themes as JSON
  } catch (error) {
    console.error("Error while fetching all Single Asset", error);
    res.status(500).json({ error: "An error occurred while fetching Single Asset" });
  }
});

**Comment by ekimcoskun** [comment]
@Furquan712 you need permission for Asset API from Shopify. 
If you think that your app is eligible for an exemption, then you can submit an exception request. 
You can find this exception form and details from here @mkevinosullivan mentioned. => https://shopify.dev/docs/apps/online-store/other-integration-methods/asset

**Comment by Furquan712** [comment]
@ekimcoskun can you please suggest to me how to get an exemption, I got rejected for an exemption request, and I want to build an app that improves performance by modifying the assets file.

**Comment by ekimcoskun** [comment]
@Furquan712 Unfortunately, I cannot give any additional advice other than what is in the document I shared. If there is a trick to get an exemption, I don't know it because I just followed the documentation.
