### ISSUE TITLE
Updating meta fields will only succeed on the first update.

### ISSUE THREAD

**Issue by Jarvie789** [Shopify/shopify-api-js#863]
# Issue summary

Updating meta fields will only succeed on the first update.

```
const client = new shopify.api.clients.Rest({ session });
  await client.put({
    path: 'pages/123456789',
    data: {
      page: {
        metafields: [
          {
            key: "data",
            value: JSON.stringify(data),
            type: "json",
            namespace: "namespace",
          }
        ]
      }
    }
  });
```

It only works after the first setting, and only when calling this API responds correctly but the page doesn't update anything. This is still the case even after I define the meta field before calling the API, so I can only delete the meta field definition before using the update page meta field, then redefine, and then call this API that sets the page meta field... This is a bit Trouble, maybe my way is wrong... Please help me, thanks in advance!

- `@shopify/shopify-api` version: 7.0.0
- Node version: 19.8.1
- Operating system: MacOS

## Expected behavior

Each call successfully sets the page's metafield data.

## Actual behavior

Requesting the API will only work if the page has no metafields bound to it.

## Steps to reproduce the problem

1.Please review the code at the top

**Comment by Jarvie127** [comment]
Please help me.😭

**Comment by Mtillmann** [comment]
@Jarvie789 did you ever resolve this? I am experiencing a very similar issue

**Comment by Jarvie789** [comment]
@Mtillmann Great, it's an easy way. 🎉
