### ISSUE TITLE
New currency support in billing request

### ISSUE THREAD

**Issue by StefanoDiLegami** [Shopify/shopify-api-js#868]
## Overview

Since API Version April23, we can charge merchants by other currencies than USD.

I would love to start using it, and therefore it would be nice if we can integrate it in this library.

**Related:**
https://shopify.dev/changelog/graphql-admin-api-now-supports-creating-app-charges-using-the-merchant-s-billing-currency

**Comment by paulomarg** [comment]
Hi, as per [our billing documentation](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/billing.md), that is already possible in the latest versions!

Since there is no action for us to take here, I'm going to close the issue, but please feel free to open a new one if you still have problems.

**Comment by StefanoDiLegami** [comment]
> Hi, as per [our billing documentation](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/billing.md), that is already possible in the latest versions!
> 
> Since there is no action for us to take here, I'm going to close the issue, but please feel free to open a new one if you still have problems.

I think we need to add currency as a new parameter in RequestParams for await shopify.api.billing.request({  }); to be able to change the currency based on shop prefered currency instead of creating an additional billing plan for each available currency.

**Comment by paulomarg** [comment]
That is a good point - what we could do here is provide arguments for `currencyCode` and `amount` when you call `request()`, so that you can override them.

I'll reopen the issue to track it, thank you!

**Comment by StefanoDiLegami** [comment]
bump
