### ISSUE TITLE
validateHmac Does Not Work For Proxy Requests

### ISSUE THREAD

**Issue by joshjacks** [Shopify/shopify-api-js#878]
# Issue summary

As of 7.0.0, the `validateHmac` function should now work for app proxy requests which send a query param called `signature` instead of `hmac`. However the verification fails, because there is a second difference. 

Usually you need to get the sha256 of the query param joined by `&`, with the proxy verification you get the sha256 joined with no delimiter, e.g.: 

Correct for proxy but not for oauth
`logged_in_customer_id=5570080145486path_prefix=/apps/yyy-customerspb=0shop=yyy-and-co.myshopify.comtimestamp=1684300797`

vs 

Correct for oauth but not for proxy
`logged_in_customer_id=5570080145486&path_prefix=/apps/yyy-customers&shop=yyy-and-co.myshopify.com&timestamp=1684300797`

- `@shopify/shopify-api` version: 7.1.0
- Node version: 18
- Operating system: MacOS

Here is an example of custom code I am using to verify the signature

```js
import { createHmac } from "crypto";

export default function verifyWebhook(query, secret) {
  const hmac = query.signature;
  const toVerify = Object.entries(query)
    .filter(([key]) => key !== "signature")
    .map(([key, value]) => `${key}=${value}`)
    .sort((a, b) => a.localeCompare(b))
    .join("");

  const calculatedHmac = createHmac("sha256", secret)
    .update(toVerify)
    .digest("hex");

  return calculatedHmac === hmac;
}
```

This verifies the signature as correct.

This difference is also in the documentation

[See here for app proxy verification without the & delimiter](https://shopify.dev/docs/apps/online-store/app-proxies#calculate-a-digital-signature) (see line 22 of the given code example)

## Steps to reproduce the problem

1. Make a request to your app via an app proxy
1. Verify the signature using `await shopifyAPI.utils.validateHmac(request.query)`
1. See that verification fails

**Comment by jonathanstanley** [comment]
I can also confirm this issue. I was just about to post an identical issue and found this. As a reference point, the following code from Shopify will not work with app proxy signature ❌:

https://github.com/Shopify/shopify-api-js/blob/21696ab6a5de1b78859421746164f1fbcea7a281/lib/utils/hmac-validator.ts#L12-L18

`processedQuery.stringify()` will inject `&` for string join, however Shopify's signature is calculated without `&`

of course the only practical way to access that function is through `validateHmac `. it seems very strange that shopify uses a contrived validation serialization for app proxy; it will predictably result in errors and app developers skipping validation entirely. not sure why Shopify doesn't just inject a JWT into the header...

in the meantime, the patch from @joshjacks is very well done https://github.com/Shopify/shopify-api-js/issues/878#issue-1713165039 (would be nice for Shopify to integrate it)
