### ISSUE TITLE
Cannot complete OAuth process. Could not find an OAuth cookie for shop url:

### ISSUE THREAD

**Issue by usama-m98** [Shopify/shopify-api-js#893]
# Issue summary

Hello,
I'm reporting an error I can't seem to resolve with my own skills, so I'll be trying to explain it the best I can, I am currently getting the following error:
CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop url:

I've gone through the issues and did notice that there was a similar error to this and it stated that the issue had been resolved in the ticket #686, but I'm not sure if it resolved the issue I'm having.

I am building the oauth process using nextjs's api routing for context and during the first oauth process the install works fine with no issues when there are no existing shopify cookies, however, this is where the problem begins. 

When the application is uninstalled and reinstalled I get the CookieNotFound error, I added a console log in the [oauth.js](https://github.com/Shopify/shopify-api-js/blob/main/lib/auth/oauth/oauth.ts) file to see what the cookies are logging and it looks like the shopify app state is undefined during the reinstall. When I delete the cookies using the browser and reinstall the application the oauth process works fine again with no issue.

This might be a non issue, but if a customer uninstalls the application and tries to reinstall, the install will fail.

- `@shopify/shopify-api` version: 7.2
- Node version: v18.14.2
- Operating system: MacOS

```
Cookies during first install in the callback function in the oauth.js file:

Cookies {
  response: {},
  receivedCookieJar: {
    shopify_app_state: { name: 'shopify_app_state', value: '114866830438584' },
    'shopify_app_state.sig': {
      name: 'shopify_app_state.sig',
      value: '/2SjTZ8YYjN2CJLCUx2OkmtDKb0OyTk+X1M4oD8XHuc='
    }
  },
  outgoingCookieJar: {},
  keys: [ 'api secret key' ]
}

Cookie during reinstall:

Cookies {
  response: {},
  receivedCookieJar: {
    shopify_app_state: { name: 'shopify_app_state', value: '' },
    'shopify_app_state.sig': {
      name: 'shopify_app_state.sig',
      value: 'kkC08jokPy+2pn7uEmIMaPsf95bK0++X13ZaRm+B1kU='
    },
    '01 Jan 1970 00:00:00 GMT': { name: '01 Jan 1970 00:00:00 GMT', value: undefined },
    auth_session: {
      name: 'auth_session',
      value: 'auth session token'
    },
    shopify_app_session: {
      name: 'shopify_app_session',
      value: 'shopify app session'
    },
    'shopify_app_session.sig': {
      name: 'shopify_app_session.sig',
      value: 'BSRRmq79QKShL/hUEfDVdL25NgSiktTVoyPFFeef3/c='
    }
  },
  outgoingCookieJar: {},
  keys: [ 'api secret key' ]
}


```

## Expected behavior

Oauth process should complete without a hitch

## Actual behavior

CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop url:

## Steps to reproduce the problem

1.
1.
1.

**Comment by jagthedrummer** [comment]
Not stale. Please turn off the bot.
