### ISSUE TITLE
The GET request from the REST client logs an obsolete warning.

### ISSUE THREAD

**Issue by indice** [Shopify/shopify-api-js#909]
# Issue summary

- `@shopify/shopify-api` version: 2023-04
- Node version: 18.5
- Operating system:  Win11, docker

My Shopify application that makes calls to a REST API. I have tested with several versions of the API and I get a deprecation warning in console.

## Expected behavior

According to [Shopify's versioning documentation](https://shopify.dev/api/usage/versioning#rest-api-deprecation-practices),

If individual properties on a resource are deprecated, then GET requests to that resource don't return the deprecation header in the response.

I would expect no warning to be logged when sending a GET request to the orders endpoint.

## Actual behavior

The following warning is logged in the console:

```
[shopify-api/WARNING] API Deprecation Notice 6/8/2023, 11:25:13 AM : {"message":"https://shopify.dev/changelog/property-deprecations-in-the-admin-api-order-and-lineitem-resource","path":"https://xxxxx.myshopify.com/admin/api/2023-04/orders.json?fields=id%2Cname"}  -  Stack Trace: Error:
    at NewRestClient.<anonymous> (/usr/src/app/node_modules/@shopify/shopify-api/lib/clients/http_client/http_client.ts:325:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:164:62)
```
## Steps to reproduce the problem
```
          const data = await getCustomerData.get({
            path: `orders`,
            query: {
              fields: "id,name",
            },
          });
```

**Comment by Zelfapp** [comment]
Issue appears to be on any REST endpoint, including using the MountedResources option.
