### ISSUE TITLE
CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop url:

### ISSUE THREAD

**Issue by elwincheng** [Shopify/shopify-api-js#933]
# Issue summary

Safari mac and iPad users unable to install Shopify app (not embedded). When calling [shopify.auth.callback](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/auth/callback.md), the following logs appear in our server:

```
[shopify-api/ERROR] Could not find OAuth cookie | {shop: llamadevstore.myshopify.com}
```

- `@shopify/shopify-api` version: ^6.2.0
- Node version: 14.19.3
- Operating system: 

Installation works fine on google chrome and windows 10

## Expected behavior

Backend should be redirect user to our frontend (app.snapwrite.ca).

## Actual behavior

Backend server encounters CookieNotFound error. Users are stuck on this url: https://apie.snapwrite.ca/shopify/authcallback?code=024b18b458864a201045097e6268c69d&hmac=f63904b34f7cc8ed36db36c29afd54750e350fff11ce731a574245f3fb15f074&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbGxhbWFkZXZzdG9yZQ&shop=llamadevstore.myshopify.com&state=999309317396318&timestamp=1688161930

## Steps to reproduce the problem
1. Use safari on mac or any browser on ipad.
1. log into app.snapwrite.ca (athiya@snapwrite.ca, Shopify123)
1. Install the app into any store https://apps.shopify.com/snapwriteai

**Comment by jsegeren** [comment]
We're also encountering the CookieNotFound [Error], as reported here, which is critical and blocking our product release.

Find a similar issue here: https://github.com/Shopify/shopify-app-template-node/issues/1282.

**Hi @paulomarg - any thoughts, updates, workarounds?** 
As a contingency, we're considering other libraries for Shopify OAuth or manual cookie management, but we'd prefer an official resolution.

```
[shopify-api/INFO] Beginning OAuth | {shop: quickstart-d81c291e.myshopify.com, isOnline: false, callbackPath: /shopify-auth/callback}
[shopify-api/INFO] Completing OAuth | {shop: quickstart-d81c291e.myshopify.com}
[shopify-api/ERROR] Could not find OAuth cookie | {shop: quickstart-d81c291e.myshopify.com}
```
