### ISSUE TITLE
Update asset endpoint not working /admin/api/2023-04/themes/828155753/assets.json

### ISSUE THREAD

**Issue by lhincapie0** [Shopify/shopify-api-js#946]
Not sure if this should be the repository to write.

I'm migrating an embedded shopify app to shopify cli 3.0.
Everything is working except when I try to use PUT assets endpoint to update a css asset.

Following the documentation in https://shopify.dev/docs/api/admin-rest/2023-07/resources/asset#put-themes-theme-id-assets, was always throwing me a 404 - not found error

After investigating could not find the error, and trying in postman the request: 

PUT:    `https://${apiKey}:${accessToken}@${shop}/admin/api/2023-07/themes/${themeId}/assets.json`;

```
const body = JSON.stringify({
      asset: {
        key: themeFile,
        value: template
      }
    });
```

Did not work as well (also tried 2023-04).

The only way is working is using API_VERSION = 2022-10, documentation is the same for both versions, so I would think is a bug because it is not finding the asset (event when the GET request is returning it)

Could you please let me know if there is something missing in the body for these new versions? or is definitely a bug?

Thank you, I would really appreciate the help to be up to date with the latest api version.

**Comment by tomoyanakano** [comment]
Hi, I'm having the same issue. the version is `2023-07`.
