### ISSUE TITLE
Do not reset remaining days from trial on uninstall

### ISSUE THREAD

**Issue by geiszla** [Shopify/shopify-api-js#958]
## Overview

We have a problem, where the trial period always resets when the user reinstalls the app. I've also read that this can be a feature, however for us it's definitely a bug, since anyone can just reinstall our app to use it for free forever.

There are a few community answers to solve this, however all of them includes changing the `trialDays` when requesting the recurring application charge. As far as I can see, the current implementation takes the trial days from the billing config, which can only be specified when creating the `shopifyApp` instance.

One option would be copying the config object with the new trial days, then using `validateConfig` manually on in, then passing it to the `request` factory function to create a request function. However, this does not seem like an intended way to use this library.

Is there any other way to do this that I missed? Otherwise, I think it would be great if we could pass the `trialDays` in when using the `shopify.api.billing.request` function to implement protection against indefinite free use of an app.

**Comment by geiszla** [comment]
@daviareias Thanks for your answer. My problem is not how I track the trial, it's how I enforce it. As far as I know Shopify will charge the merchant as soon as my trial ends. My issue is that I cannot find an obvious way of setting different trial days for different users (e.g. the user who uninstalls then reinstalls the app 2 days later should have 2 less days of trials than a completely new user).

I see 3 solutions (all of them looks somewhat hacky):

1. I create a new `shopifyApp` object when a new user comes to set the proper trial dates (sounds error prone, and I don't think it was intended to be used this way).
2. Create a new config, validate it manually, then create a request function (as described in the OP) to use to request a subscription for the current user.
3. Create as many billing plans as there are trial days and pass them all in the initial config to one instance of `shopifyApp`. This seems to be the most "innocent" solution, but also the ugliest.

Let me know if I missed something or misunderstood how this should be done.

**Comment by paulomarg** [comment]
Hey folks, thanks for reporting this. I think we can help remedy this by allowing an optional override for `trialDays` when you're calling `request`!
