### ISSUE TITLE
How to set InventoryLevel ?

### ISSUE THREAD

**Issue by an0o0nym** [Shopify/shopify-api-js#976]
## Overview

Is there any way you support this action ? 
https://shopify.dev/docs/api/admin-rest/2023-07/resources/inventorylevel#post-inventory-levels-set

**Comment by lizkenyon** [comment]
Hi there 👋 

Thanks for reaching out! 

I believe this question is best suited for the for our [developer forums.](https://community.shopify.com/c/partners-and-developers/ct-p/appdev)

If you are able to describe the context in which you will be making the request (e.g Remix template, node, ect) someone may be able to provide supplementary context to the documentation your reached.
