### ISSUE TITLE
shopify.auth.begin throws "TypeError: adapterArgs.rawResponse.getHeaders is not a function"

### ISSUE THREAD

**Issue by ikehiemma** [Shopify/shopify-api-js#977]
# Issue summary

I'm building a non-embedded Shopify app using NextJS (v13.4.12) app router and I'm having difficulties performing authentication with the shopify API. I've read the docs and not sure what I could be missing and hoping someone could help me out here. When I call the `/api/integrations/shopify` endpoint in my app to initiate the authentication, I get the error below:

```
[2023-09-05T09:40:03Z] [shopify-api/INFO] Beginning OAuth | {shop: [shop-name].myshopify.com, isOnline: false, callbackPath: /api/integrations/shopify/callback/}
TypeError: adapterArgs.rawResponse.getHeaders is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/@shopify/shopify-api/adapters/node/adapter.js:27:78)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///(rsc)/./node_modules/tslib/tslib.es6.mjs:179:71)
    at new Promise (<anonymous>)
    at Module.__awaiter (webpack-internal:///(rsc)/./node_modules/tslib/tslib.es6.mjs:161:12)
    at nodeConvertIncomingResponse (webpack-internal:///(rsc)/./node_modules/@shopify/shopify-api/adapters/node/adapter.js:23:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@shopify/shopify-api/lib/auth/oauth/oauth.js:42:79)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///(rsc)/./node_modules/tslib/tslib.es6.mjs:164:32)
```

Here is my endpoint implementation in `/api/integrations/shopify/route.ts`:
```ts
import { shopify } from "@/app/utils/shopify";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest, response: NextResponse) {
  try {
    const storeDomain = request.nextUrl.searchParams.get("storeDomain");

    const callbackPath = `/api/integrations/shopify/callback/`;

    await shopify.auth.begin({
      shop: shopify.utils.sanitizeShop(storeDomain, true),
      callbackPath: callbackPath,
      isOnline: false,
      rawRequest: request,
      rawResponse: response,
    });

  } catch (error) {
    console.log(error);
    return NextResponse.json(
      {
        status: "error",
        code: "INTERNAL_SERVER_ERROR",
        message: "Integration with Shopify failed",
        details: error.message,
        path: "/api/integrations/shopify",
        timestamp: new Date().toISOString(),
      },
      { status: 500 }
    );
  }
}
```

Here is how I'm setting up my shopifyApi object in a `shopify.ts` file:
```ts
import "@shopify/shopify-api/adapters/node";
import { shopifyApi, ApiVersion } from "@shopify/shopify-api";
import { restResources } from "@shopify/shopify-api/rest/admin/2023-07";
import { SHOPIFY_SCOPES } from "@/app/utils/constants";

export const shopify = shopifyApi({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET_KEY,
  scopes: SHOPIFY_SCOPES,
  hostName: process.env.NEXT_PUBLIC_APP_BASE_URL,
  hostScheme: "http",
  isEmbeddedApp: false,
  apiVersion: ApiVersion.July23,
  restResources,
});
```

- `@shopify/shopify-api` version: 7.6.0
- Node version: v18.16.1
- Operating system: macOS

## Expected behavior

I should be redirected to the Shopify authorisation page where I'm asked to install the app.

## Actual behavior

I get the `TypeError: adapterArgs.rawResponse.getHeaders is not a function` error.

## Steps to reproduce the problem

1. Start a new NextJS app using `npx create-next-app@latest`. Choose the App Router when prompted.
1. Create an API endpoint in the `app` folder, for example `/api/integrations/shopify/route.ts` and use the code above
1. Set up the shopify API object
2. Run `npm run start` to start the server.
3. Call the endpoint: `http://localhost:3000/api/integrations/shopify?storeDomain=[shop].myshopify.com

**Comment by ikehiemma** [comment]
After some digging, I stumbled on this [comment](https://github.com/Shopify/shopify-api-js/issues/893#issuecomment-1597300152) which help me resolved this issue. I used the NextJS App Router template which implemented a custom adapter.

**Comment by jonathanstanley** [comment]
> After some digging, I stumbled on this [comment](https://github.com/Shopify/shopify-api-js/issues/893#issuecomment-1597300152) which help me resolved this issue. I used the NextJS App Router template which implemented a custom adapter.

I have a similar issue. If you could clarify how the comment helped, it would be appreciated!

**Comment by jjrise** [comment]
thanks for the insight @ikehiemma! So I am having the exact same issue as you in next 14. I also tried implementing the custom adapter you referenced but get a slightly different error:
`TypeError: Cannot read properties of undefined (reading 'getRandomValues')`

Did you ever make any more progress on this or did you stick with the custom adapter that worked for you? Thanks!
