### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by anssip** [Shopify/shopify-api-js#996]
I have a couple of questions:

1. Do i need to perform the OAuth flow at all in my Shopify app if I just intend to register webhooks?
2. What is the meaning of `isEmbeddedApp` setting in the `shopifyApi` call? See below.
3. Shoud i use `shopifyApi()` call like in below or perhaps `shopifyApp()`? What is the difference?

```TypeScript
const shopify = shopifyApi({
  // The next 4 values are typically read from environment variables for added security
  apiKey: '***',
  apiSecretKey: '***',
  scopes: ['read_products','read_orders'],
  hostName: 'https://0da444b73168.ngrok.app',
  apiVersion: LATEST_API_VERSION,
  isEmbeddedApp: false, // ?????
  logger: {
    log: (severity, message) => {
      console.log("message",message);
    },
    httpRequests:true,
    level: LogSeverity.Debug
  },
});
```

**Comment by lizkenyon** [comment]
Hi there 👋 

_Do i need to perform the OAuth flow at all in my Shopify app if I just intend to register webhooks?_
If you are intending to create a public app then you will need to go through the OAuth flow, as you need merchant to Authorize your app to have access to the data that the webhooks would return. If your app is only going to be connected to one store then OAuth is not required. For more information on App Authorization for different types of apps you can review the [documentation](https://help.shopify.com/en/manual/apps/app-types/custom-apps). 

_What is the meaning of isEmbeddedApp setting in the shopifyApi call? See below._
For more information on the properties of the shopify object, please review the [documentation](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/reference/shopifyApi.md#isembeddedapp). The isEmbeddedApp setting determines whether your application's UI will show in an iframe within the Shopify Admin. 

_Shoud i use shopifyApi() call like in below or perhaps shopifyApp()? What is the difference?_
Shopify API is a thin wrapper around making API calls to Shopify. [Shopify App ](https://github.com/Shopify/shopify-app-js)is a collection of packages that make it easy for apps to integrate with Shopify. They all build on top of the [@shopify/shopify-api](https://github.com/Shopify/shopify-api-js) package to cover specific use cases.
